create table MED_MEDICALSTATUS
(
  MEDICALSTATUSID number(38) not null,
  COMPANYID       number(38) not null,
  MNEMONIC        varchar2(20) not null,
  DESCR           varchar2(100) not null,
  ISACTIVE        varchar2(20) not null
);

alter table MED_MEDICALSTATUS
  add constraint PK_MEDICALSTATUS primary key (MEDICALSTATUSID, COMPANYID);


create table MED_STATUSPATTERNHEADER
(
  STATUSPATTERNHEADERID number(38) not null,
  COMPANYID             number(38) not null,
  MNEMONIC              varchar2(20) not null,
  DESCR                 varchar2(200) not null,
  ISACTIVE              varchar2(20) not null
);

alter table MED_STATUSPATTERNHEADER
  add constraint PK_MED_STATUSPATTERNHD primary key (STATUSPATTERNHEADERID, COMPANYID);

create table MED_STATUSPATTERNDETAIL
(
  STATUSPATTERNDETAILID number(38) not null,
  STATUSPATTERNHEADERID number(38) not null,
  COMPANYID             number(38) not null,
  MEDICALSTATUSID       number(38) not null,
  PRIORITY              number(38) not null,
  ISDEFAULT             varchar2(1) not null
);

alter table MED_STATUSPATTERNDETAIL
  add constraint PK_MED_STATUSPATTERNDT primary key (STATUSPATTERNDETAILID, COMPANYID);
alter table MED_STATUSPATTERNDETAIL
  add constraint FK_STATUSPTRNDT_MED_STATUS foreign key (MEDICALSTATUSID, COMPANYID)
  references med_medicalstatus (MEDICALSTATUSID, COMPANYID) on delete cascade;
alter table MED_STATUSPATTERNDETAIL
  add constraint FK_STATUSPTRNDT_PTRNHD foreign key (STATUSPATTERNHEADERID, COMPANYID)
  references med_statuspatternheader (STATUSPATTERNHEADERID, COMPANYID);

create index FK_STATUSPTRNDT_MED_STATUS on MED_STATUSPATTERNDETAIL (medicalstatusid, companyid);
create index FK_STATUSPTRNDT_PTRNHD on MED_STATUSPATTERNDETAIL (statuspatternheaderid, companyid);

create table MED_SERVICESTATUSLOG
(
  SERVICESTATUSLOGID number(38) not null,
  COMPANYID          number(38) not null,
  SERVICEID          number(38) not null,
  NEWSERVICESTATUSID number(38) not null,
  SYSLOGDATE         date not null,
  SYSLOGTIME         timestamp(6) not null,
  LOGUSERNAME        varchar2(20) not null,
  LOGDATE            date not null,
  LOGTIME            timestamp(6) not null,
  ISFIRSTLOG         varchar2(1) not null 
);

alter table MED_SERVICESTATUSLOG
  add constraint PK_SERVICESTATUSLOG primary key (SERVICESTATUSLOGID, COMPANYID);
alter table MED_SERVICESTATUSLOG
  add constraint FK_SRVSTATUSLOG_SERVICE foreign key (SERVICEID, COMPANYID)
  references med_service (SERVICEID, COMPANYID);
alter table MED_SERVICESTATUSLOG
  add constraint FK_SRVSTATUSLOG_MEDCLSTATUS foreign key (NEWSERVICESTATUSID, COMPANYID)
  references med_medicalstatus (MEDICALSTATUSID, COMPANYID);

create index FK_SRVSTATUSLOG_SERVICE on MED_SERVICESTATUSLOG (serviceid, companyid);
create index FK_SRVSTATUSLOG_MEDCLSTATUS on MED_SERVICESTATUSLOG (newservicestatusid, companyid);
create index LOGDATE_TIME_INDX on MED_SERVICESTATUSLOG (logdate, logtime);

alter table MED_PARAMETERS add DEFSTATUSPATTERNHEADERID number(38);
alter table MED_SERVICEMASTER add STATUSPATTERNHEADERID number(38);
alter table MED_SERVICE add MEDICALSTATUSID number(38);

CREATE SEQUENCE MED_MEDICALSTATUS_SEQ START WITH 2
INSERT INTO SYS_SEQUENCE (COMPANYID,FYEARID,OBJECTID,COUNTER,OBJECTDESCRIPTION) VALUES (1,0,'MED_MEDICALSTATUS',2,'MEDICAL STATUS TABLE');
INSERT INTO MED_MEDICALSTATUS(COMPANYID,DESCR,MEDICALSTATUSID,MNEMONIC,ISACTIVE) VALUES (1,'MEDICAL VALIDATED',1,'MEDICAL VALIDATED','1');
COMMIT;

CREATE SEQUENCE MED_STATUSPATTERNHEADER_SEQ START WITH 2
INSERT INTO SYS_SEQUENCE (COMPANYID,FYEARID,OBJECTID,COUNTER,OBJECTDESCRIPTION) VALUES (1,0,'MED_STATUSPATTERNHEADER',2,'MEDICAL STATUS PATTERN HEADER TABLE');
INSERT INTO MED_STATUSPATTERNHEADER(COMPANYID,DESCR,MNEMONIC,STATUSPATTERNHEADERID,ISACTIVE) VALUES (1,'DEFAULT PATTERN','DEFAULT PATTERN',1,'1');
INSERT INTO SYS_SEQUENCE (COMPANYID,FYEARID,OBJECTID,COUNTER,OBJECTDESCRIPTION) VALUES (1,0,'MED_STATUSPATTERNDETAIL',2,'MEDICAL STATUS PATTERN DETAIL TABLE');
INSERT INTO MED_STATUSPATTERNDETAIL(COMPANYID,ISDEFAULT,MEDICALSTATUSID,PRIORITY,STATUSPATTERNDETAILID,STATUSPATTERNHEADERID) VALUES (1,'1',1,1,1,1);
COMMIT;

UPDATE MED_PARAMETERS SET DEFSTATUSPATTERNHEADERID = 1;
COMMIT;

alter table MED_PARAMETERS modify DEFSTATUSPATTERNHEADERID not null;
