ALTER TABLE PLG_BUDGETDETAIL ADD BUDGETC FLOAT(126);
ALTER TABLE PLG_BUDGETRESDETAIL ADD ISBUDGETC VARCHAR2(1) DEFAULT '0';
ALTER TABLE PLG_BUDGETEXEC ADD ISBUDGETC VARCHAR2(1) DEFAULT '0';
UPDATE PLG_BUDGETRESDETAIL SET ISBUDGETC = '0';
UPDATE PLG_BUDGETEXEC SET ISBUDGETC = '0';
COMMIT;
ALTER TABLE FIN_TRANSHEADER ADD ISBUDGETC VARCHAR2(1) DEFAULT '0';
ALTER TABLE FIN_TRANSDETAIL ADD ISBUDGETC VARCHAR2(1) DEFAULT '0';
UPDATE FIN_TRANSHEADER SET ISBUDGETC = '0' WHERE EVENTTYPEINDICATOR = 1;
UPDATE FIN_TRANSDETAIL SET ISBUDGETC = '0' WHERE EVENTTYPEINDICATOR = 1;



