CREATE TABLE PBL_EUROPEANINSURANCE (
  COMPANYID NUMBER(38) NOT NULL,
  EUROPEANINSURANCEID NUMBER(38) NOT NULL,
  COUNTRYID NUMBER(38) ,
  DESCR VARCHAR2(200) NOT NULL,
  DAPYCODE VARCHAR2(10) NOT NULL,
  ISACTIVE VARCHAR2(1) NOT NULL
);
ALTER TABLE PBL_EUROPEANINSURANCE
   ADD CONSTRAINT PBL_EUROPEANINSURANCE_PK
   PRIMARY KEY(EUROPEANINSURANCEID, COMPANYID);
ALTER TABLE PBL_EUROPEANINSURANCE
   ADD CONSTRAINT SYS_COUNTRY_EUROPEANINSUR_FK
   FOREIGN KEY(COUNTRYID)
   REFERENCES SYS_COUNTRY(COUNTRYID);

ALTER TABLE PBL_VISITCOVERDETAIL ADD (
  EUROPEANINSURANCEID NUMBER(38),
  INSURANCECATEGORYINDICATOR NUMBER(38) DEFAULT 0,
  APPROVALDOCTORID NUMBER(38)
);
ALTER TABLE PBL_VISITCOVERDETAIL
  ADD CONSTRAINT PBL_EURINSUR_VISITCOVER_FK
  FOREIGN KEY(EUROPEANINSURANCEID, COMPANYID)
  REFERENCES PBL_EUROPEANINSURANCE(EUROPEANINSURANCEID, COMPANYID);
ALTER TABLE PBL_VISITCOVERDETAIL
  ADD CONSTRAINT APPROVALDOCTOR_VISITCOVER_FK
  FOREIGN KEY(APPROVALDOCTORID, COMPANYID, FYEARID)
  REFERENCES PTA_DOCTOR(DOCTORID, COMPANYID, FYEARID);

