CREATE TABLE PTA_EOPYYHL7MSG (
  EOPYYHL7MSGID NUMBER(38) NOT NULL,
  COMPANYID NUMBER(38) NOT NULL,
  VISITID NUMBER(38) NOT NULL,
  FYEARID NUMBER(38) NOT NULL,
  EVENTINDICATOR NUMBER(38) NOT NULL,
  EVENTNO VARCHAR2(20) NOT NULL,
  VISITADMISSIONID NUMBER(38),
  VISITDISCHARGEID NUMBER(38),
  TRANSFERID NUMBER(38),
  VISITADMISSIONCANCELID NUMBER(38),
  VISITDISCHARGECANCELID NUMBER(38),
  MESSAGEDATE DATE,
  MESSAGETIME TIMESTAMP(6),
  MESSAGE VARCHAR2(2000),
  RESPONSE VARCHAR2(2000),
  SENDSTATUS NUMBER(38) NOT NULL
);
ALTER TABLE PTA_EOPYYHL7MSG
  ADD CONSTRAINT PTA_EOPYYHL7MSG_PK
  PRIMARY KEY(EOPYYHL7MSGID, COMPANYID);

ALTER TABLE PTA_EOPYYHL7MSG
  ADD CONSTRAINT PTA_VISIT_EOPYYHL7MSG_FK
  FOREIGN KEY(VISITID, COMPANYID, FYEARID)
  REFERENCES PTA_VISIT(VISITID, COMPANYID, FYEARID);

ALTER TABLE PTA_EOPYYHL7MSG
  ADD CONSTRAINT PTA_VISITADM_EOPYYHL7MSG_FK
  FOREIGN KEY(VISITADMISSIONID, COMPANYID, FYEARID)
  REFERENCES PTA_VISITADMISSION(VISITADMISSIONID, COMPANYID, FYEARID);

ALTER TABLE PTA_EOPYYHL7MSG
  ADD CONSTRAINT PTA_VISITDIS_EOPYYHL7MSG_FK
  FOREIGN KEY(VISITDISCHARGEID, COMPANYID, FYEARID)
  REFERENCES PTA_VISITDISCHARGE(VISITDISCHARGEID, COMPANYID, FYEARID);

ALTER TABLE PTA_EOPYYHL7MSG
  ADD CONSTRAINT PTA_TRANSFER_EOPYYHL7MSG_FK
  FOREIGN KEY(TRANSFERID, COMPANYID, FYEARID)
  REFERENCES PTA_TRANSFER(TRANSFERID, COMPANYID, FYEARID);

ALTER TABLE PTA_EOPYYHL7MSG
  ADD CONSTRAINT PTA_ADMCANCEL_EOPYYHL7MSG_FK
  FOREIGN KEY(VISITADMISSIONCANCELID, COMPANYID, FYEARID)
  REFERENCES PTA_VISITADMISSIONCANCEL(VISITADMISSIONCANCELID, COMPANYID, FYEARID);

ALTER TABLE PTA_EOPYYHL7MSG
  ADD CONSTRAINT PTA_DISCANCEL_EOPYYHL7MSG_FK
  FOREIGN KEY(VISITDISCHARGECANCELID, COMPANYID, FYEARID)
  REFERENCES PTA_VISITDISCHARGECANCEL(VISITDISCHARGECANCELID, COMPANYID, FYEARID);

CREATE INDEX PTA_VISIT_EOPYYHL7MSG_FK ON PTA_EOPYYHL7MSG(VISITID, COMPANYID, FYEARID);
CREATE INDEX PTA_VISITADM_EOPYYHL7MSG_FK ON PTA_EOPYYHL7MSG(VISITADMISSIONID, COMPANYID, FYEARID);
CREATE INDEX PTA_VISITDIS_EOPYYHL7MSG_FK ON PTA_EOPYYHL7MSG(VISITDISCHARGEID, COMPANYID, FYEARID);
CREATE INDEX PTA_TRANSFER_EOPYYHL7MSG_FK ON PTA_EOPYYHL7MSG(TRANSFERID, COMPANYID, FYEARID);
CREATE INDEX PTA_ADMCANCEL_EOPYYHL7MSG_FK ON PTA_EOPYYHL7MSG(VISITADMISSIONCANCELID, COMPANYID, FYEARID);
CREATE INDEX PTA_DISCANCEL_EOPYYHL7MSG_FK ON PTA_EOPYYHL7MSG(VISITDISCHARGECANCELID, COMPANYID, FYEARID);

CREATE INDEX PTA_EOPYYHL7MSG_STATUS ON PTA_EOPYYHL7MSG(COMPANYID, FYEARID, SENDSTATUS);
