CREATE TABLE PTA_EOPYYPARAMETERS (
  COMPANYID NUMBER(38) NOT NULL,
  FYEARID NUMBER(38) NOT NULL,
  HOSPITALNAME VARCHAR2(100),
  HOSPITALCODE VARCHAR2(10),
  CONTRACTNUM_OUTP VARCHAR2(20),
  CONTRACTNUM_INP VARCHAR2(20),
  FINITEMCODINGID_SERVICETYPE NUMBER(38),
  FINITEMCODINGID_SERVICECODE NUMBER(38),
  FINITEMCODINGID_EOF NUMBER(38),
  FINITEMCODINGID_EKAPTY NUMBER(38),
  FINITEMCODINGID_PARATIRITIRIO NUMBER(38),
  EPRESCR_ISCONNECTINGTOWS VARCHAR2(1) NOT NULL,
  EPRESCR_ISUSINGPROXY VARCHAR2(1) NOT NULL,
  EPRESCR_PROXY VARCHAR2(30),
  EPRESCR_PROXYPORT VARCHAR2(10),
  EPRESCR_USERNAME VARCHAR2(20),
  EPRESCR_PASSWORD VARCHAR2(20),
  EPRESCR_DIGITALCERTIFICATENUM VARCHAR2(30),
  EPRESCR_CLIENTKEYSTOREFILE VARCHAR2(20),
  EPRESCR_CLIENTKEYSTOREPASSWORD VARCHAR2(20),
  EPRESCR_CLIENTKEYALIAS VARCHAR2(20),
  EPRESCR_CLIENTKEYPASSWORD VARCHAR2(20),
  EPRESCR_CERTFILE VARCHAR2(20)
);

ALTER TABLE PTA_EOPYYPARAMETERS
  ADD CONSTRAINT PTA_EOPYYPARAMETERS_PK
  PRIMARY KEY(COMPANYID, FYEARID);

ALTER TABLE PTA_EOPYYPARAMETERS
  ADD CONSTRAINT SERVICETYPE_EOPYYPARAMETERS_FK
  FOREIGN KEY(FINITEMCODINGID_SERVICETYPE, COMPANYID, FYEARID)
  REFERENCES FIN_ITEMCODING(FINITEMCODINGID, COMPANYID, FYEARID);

ALTER TABLE PTA_EOPYYPARAMETERS
  ADD CONSTRAINT SERVICECODE_EOPYYPARAMETERS_FK
  FOREIGN KEY(FINITEMCODINGID_SERVICECODE, COMPANYID, FYEARID)
  REFERENCES FIN_ITEMCODING(FINITEMCODINGID, COMPANYID, FYEARID);

ALTER TABLE PTA_EOPYYPARAMETERS
  ADD CONSTRAINT EOF_EOPYYPARAMETERS_FK
  FOREIGN KEY(FINITEMCODINGID_EOF, COMPANYID, FYEARID)
  REFERENCES FIN_ITEMCODING(FINITEMCODINGID, COMPANYID, FYEARID);

ALTER TABLE PTA_EOPYYPARAMETERS
  ADD CONSTRAINT EKAPTY_EOPYYPARAMETERS_FK
  FOREIGN KEY(FINITEMCODINGID_EKAPTY, COMPANYID, FYEARID)
  REFERENCES FIN_ITEMCODING(FINITEMCODINGID, COMPANYID, FYEARID);

ALTER TABLE PTA_EOPYYPARAMETERS
  ADD CONSTRAINT PARATIR_EOPYYPARAMETERS_FK
  FOREIGN KEY(FINITEMCODINGID_PARATIRITIRIO, COMPANYID, FYEARID)
  REFERENCES FIN_ITEMCODING(FINITEMCODINGID, COMPANYID, FYEARID);
