CREATE TABLE PBL_EOPYYPRICE(SERVICETYPE VARCHAR2(2) NOT NULL, CODING VARCHAR2(2) NOT NULL, 
  SERVICECODE VARCHAR2(30) NOT NULL, PRICE FLOAT(126), DESCR VARCHAR2(1000), COMMENTS VARCHAR2(100));
ALTER TABLE PBL_EOPYYPRICE ADD PRIMARY KEY (CODING, SERVICECODE);
