CREATE TABLE SYS_MAILPARAMS (
  COMPANYID NUMBER(38) NOT NULL,
  SMTPHOST VARCHAR2(100) NOT NULL,
  SMTPPORT NUMBER(38),
  USERNAME VARCHAR2(100) NOT NULL,
  PASSWORD VARCHAR2(100) NOT NULL
);
ALTER TABLE SYS_MAILPARAMS
  ADD CONSTRAINT SYS_MAILPARAMS_PK
  PRIMARY KEY(COMPANYID);

CREATE TABLE SYS_MAILLISTGROUP (
  MAILLISTGROUPID NUMBER(38) NOT NULL,
  COMPANYID NUMBER(38) NOT NULL,
  MNEMONIC VARCHAR2(20) NOT NULL,
  DESCR VARCHAR2(100) NOT NULL,
  ISACTIVE VARCHAR2(1) DEFAULT '1' NOT NULL,
  SENDEREMAIL VARCHAR2(50) NOT NULL,
  SUBJECT VARCHAR2(100) NOT NULL,
  REPORTID NUMBER(38)
);
ALTER TABLE SYS_MAILLISTGROUP
  ADD CONSTRAINT SYS_MAILLISTGROUP_PK
  PRIMARY KEY(MAILLISTGROUPID, COMPANYID);

CREATE TABLE SYS_MAILLIST (
  MAILLISTID NUMBER(38) NOT NULL,
  COMPANYID NUMBER(38) NOT NULL,
  MAILLISTGROUPID NUMBER(38),
  DESCR VARCHAR2(100) NOT NULL,
  CREATIONDATE DATE NOT NULL,
  SENDEREMAIL VARCHAR2(50) NOT NULL,
  SUBJECT VARCHAR2(100) NOT NULL,
  MAILLISTSTATUSINDICATOR NUMBER(38) DEFAULT 1 NOT NULL,
  SCHEDULEDATE DATE NOT NULL,
  SCHEDULETIME TIMESTAMP(6) NOT NULL,
  REPORTID NUMBER(38)
);
ALTER TABLE SYS_MAILLIST
  ADD CONSTRAINT SYS_MAILLIST_PK
  PRIMARY KEY(MAILLISTID, COMPANYID);
ALTER TABLE SYS_MAILLIST
  ADD CONSTRAINT SYS_MAILLISTGROUP_LIST_FK
  FOREIGN KEY(MAILLISTGROUPID, COMPANYID)
  REFERENCES SYS_MAILLISTGROUP(MAILLISTGROUPID, COMPANYID);
CREATE INDEX SYS_MAILLIST_STATUS_IDX ON SYS_MAILLIST(COMPANYID, MAILLISTSTATUSINDICATOR);

CREATE TABLE SYS_MAILLISTRECIPIENT (
  MAILLISTRECIPIENTID NUMBER(38) NOT NULL,
  COMPANYID NUMBER(38) NOT NULL,
  MAILLISTID NUMBER(38) NOT NULL,
  FINTRANSPARTYID NUMBER(38),
  FYEARID NUMBER(38),
  RECIPIENTNAME VARCHAR2(100) NOT NULL,
  RECIPIENTEMAIL VARCHAR2(50) NOT NULL,
  CONTENTS CLOB,
  MAILSTATUSINDICATOR NUMBER(38) DEFAULT 1 NOT NULL
);
ALTER TABLE SYS_MAILLISTRECIPIENT
   ADD CONSTRAINT SYS_MAILLISTRECIPIENT_PK
   PRIMARY KEY(MAILLISTRECIPIENTID, COMPANYID);
ALTER TABLE SYS_MAILLISTRECIPIENT
   ADD CONSTRAINT SYS_MAILLIST_RECIPIENT_FK
   FOREIGN KEY(MAILLISTID, COMPANYID)
   REFERENCES SYS_MAILLIST(MAILLISTID, COMPANYID)
   ON DELETE CASCADE;
ALTER TABLE SYS_MAILLISTRECIPIENT
  ADD CONSTRAINT FIN_TRANSPARTY_MAILLISTREC_FK
  FOREIGN KEY(FINTRANSPARTYID, COMPANYID, FYEARID)
  REFERENCES FIN_TRANSPARTY(FINTRANSPARTYID, COMPANYID, FYEARID);
CREATE INDEX SYS_MAILLIST_RECIPIENT_FK ON SYS_MAILLISTRECIPIENT(MAILLISTID, COMPANYID);

CREATE TABLE SYS_MAILLISTHISTORY (
  MAILLISTHISTORYID NUMBER(38) NOT NULL,
  COMPANYID NUMBER(38) NOT NULL,
  MAILLISTRECIPIENTID NUMBER(38) NOT NULL,
  ATTEMPTDATE DATE NOT NULL,
  ATTEMPTTIME TIMESTAMP(6),
  ATTEMPTSTATUSINDICATOR NUMBER(38) NOT NULL
);
ALTER TABLE SYS_MAILLISTHISTORY
  ADD CONSTRAINT SYS_MAILLISTHISTORY_PK
  PRIMARY KEY(MAILLISTHISTORYID, COMPANYID);
ALTER TABLE SYS_MAILLISTHISTORY
  ADD CONSTRAINT SYS_MAILLISTRECIP_HISTORY_FK
  FOREIGN KEY(MAILLISTRECIPIENTID, COMPANYID)
  REFERENCES SYS_MAILLISTRECIPIENT(MAILLISTRECIPIENTID, COMPANYID)
  ON DELETE CASCADE;
CREATE INDEX SYS_MAILLISTRECIP_HISTORY_FK ON SYS_MAILLISTHISTORY (MAILLISTRECIPIENTID, COMPANYID);

