alter table INV_PARAMETERS drop column REPLENISHITEMBEHAVIORID;
alter table INV_PARAMETERS add REPLENISHITEMBEHAVIORINDICATOR number(38);

UPDATE INV_PARAMETERS SET REPLENISHITEMBEHAVIORINDICATOR = 1;
COMMIT;

alter table INV_PARAMETERS modify REPLENISHITEMBEHAVIORINDICATOR not null;
REPLENISHITEMBEHAVIORID