ALTER TABLE PTA_VISITPARTSCHEME ADD(VALIDSINCEDATE DATE, VALIDTILLDATE DATE);
UPDATE PTA_VISITPARTSCHEME SET VALIDSINCEDATE = TO_DATE('01-01-2000', 'DD-MM-YYYY');
COMMIT;
ALTER TABLE PTA_VISITPARTSCHEME MODIFY VALIDSINCEDATE NOT NULL;
