alter table PBL_VISITCOVERDETAIL add APPROVALAYENO varchar2(20);
alter table PBL_VISITCOVERDETAIL add APPROVALENDDATE date;
alter table PBL_VISITCOVERDETAIL add PROTOCOLNOEXPOPINION varchar2(20);

alter table PBL_VISITCOVERDETAIL add REFERENCENO VARCHAR2(20);
alter table PBL_VISITCOVERDETAIL add ISSUEDATE date;
alter table PBL_VISITCOVERDETAIL add INSURCOUNTRYID number(38);
alter table PBL_VISITCOVERDETAIL add REFAPPROVALDATE date;
