-- Create table
create table INV_ITEMGRPCODEITEMGRPCODE
(
  INVITEMGRPCODEITEMGRPCODEID NUMBER(38) not null,
  INVITEMGROUPINGID           NUMBER(38) not null,
  INVITEMGROUPINGCODE         VARCHAR2(40) not null,
  FINITEMGROUPINGID           NUMBER(38) not null,
  FINITEMGROUPINGCODE         VARCHAR2(40) not null,
  COMPANYID                   NUMBER(38) not null,
  FYEARID                     NUMBER(38) not null
);

-- Create/Recreate primary, unique and foreign key constraints 
alter table INV_ITEMGRPCODEITEMGRPCODE
  add constraint PK_ITEMGRPCODEITEMGRPCODE primary key (INVITEMGRPCODEITEMGRPCODEID, COMPANYID, FYEARID);

alter table INV_ITEMGRPCODEITEMGRPCODE
  add constraint FK_INVITMGRPCOD_FINITEMGRPCOD foreign key (FINITEMGROUPINGID, FINITEMGROUPINGCODE, COMPANYID, FYEARID)
  references fin_itemGROUPINGCODE (FINITEMGROUPINGID, FINITEMGROUPINGCODE, COMPANYID, FYEARID);
alter table INV_ITEMGRPCODEITEMGRPCODE
  add constraint FK_ITEMGRPCODE_INViTEMGRPCODE foreign key (INVITEMGROUPINGID, INVITEMGROUPINGCODE, COMPANYID, FYEARID)
  references inv_itemGROUPINGCODE (INVITEMGROUPINGID, INVITEMGROUPINGCODE, COMPANYID, FYEARID) on delete cascade;
-- Create/Recreate indexes 
create index FK_INVITMGRPCOD_FINITEMGRPCOD on INV_ITEMGRPCODEITEMGRPCODe (FINITEMGROUPINGID, FINITEMGROUPINGCODE, COMPANYID, FYEARID);
create index FK_ITEMGRPCODE_INVITEMGRPCODE on INV_ITEMGRPCODEITEMGRPCODe (INVITEMGROUPINGID, INVITEMGROUPINGCODE, COMPANYID, FYEARID);
