CREATE TABLE SYS_ADDITIONALFIELD(ADDITIONALFIELDID NUMBER(38) NOT NULL,
  COMPANYID NUMBER(38) NOT NULL, MNEMONIC VARCHAR2(20) NOT NULL, 
  DESCR VARCHAR2(100) NOT NULL, ISACTIVE VARCHAR2(1) NOT NULL,
  DATATYPEINDICATOR NUMBER(38) NOT NULL, COMPONENTTYPE NUMBER(38) NOT NULL,
  COMPSIZE NUMBER(38), MAXLENGTH NUMBER(38), SCALE NUMBER(38), ISSYSMETADATADROPDOWN VARCHAR2(1) NOT NULL,
  SYSMETADATAID VARCHAR2(50), SYSMETADATASINCEVALUE NUMBER(38), SYSMETADATATILLVALUE NUMBER(38),
  DROPDOWNTABLENAME VARCHAR2(50), DROPDOWNTABLECRITERIA VARCHAR2(100), DROPDOWNKEYCOLUMN VARCHAR2(50),
  DROPDOWNDISPLAYCOLUMN VARCHAR2(50), ISDROPDOWNCOMPANYDEPENDENT VARCHAR2(1) NOT NULL,
  ISDROPDOWNFYEARDEPENDENT VARCHAR2(1) NOT NULL, DEFAULTISREQUIRED VARCHAR2(1) NOT NULL,
  LOOKUPCOMPONENT VARCHAR2(50), DEFAULTWIDTH NUMBER(38), DEFAULTHEIGHT NUMBER(38));

ALTER TABLE SYS_ADDITIONALFIELD ADD CONSTRAINT SYS_ADDITIONALFIELD_PK PRIMARY KEY (ADDITIONALFIELDID, COMPANYID);

CREATE TABLE SYS_ENTRYCUSTOMIZATION(ENTRYCUSTOMIZATIONID NUMBER(38) NOT NULL, COMPANYID NUMBER(38) NOT NULL,
  PAGE VARCHAR2(100) NOT NULL, USERNAME VARCHAR2(20), ENTRYDEFINITION CLOB);

ALTER TABLE SYS_ENTRYCUSTOMIZATION ADD CONSTRAINT SYS_ENTRYCUSTOMIZATION_PK PRIMARY KEY (ENTRYCUSTOMIZATIONID, COMPANYID);

ALTER TABLE SYS_ENTRYCUSTOMIZATION ADD CONSTRAINT SYS_USER_ENTRYCUSTOMIZATION 
  FOREIGN KEY (USERNAME, COMPANYID) REFERENCES SYS_USER (USERNAME, COMPANYID);

CREATE TABLE SYS_ENTRYADDITIONALFIELD(ENTRYADDITIONALFIELDID NUMBER(38) NOT NULL,
  COMPANYID NUMBER(38) NOT NULL, OBJECTPK VARCHAR2(300) NOT NULL,
  ADDITIONALFIELDID NUMBER(38) NOT NULL, DATATYPEINDICATOR NUMBER(38) NOT NULL,
  FIELDVALUE VARCHAR2(255), PAGE VARCHAR2(100) NOT NULL, NAME VARCHAR2(30) NOT NULL);
ALTER TABLE SYS_ENTRYADDITIONALFIELD ADD CONSTRAINT SYS_ENTRYADDITIONALFIELD_PK PRIMARY KEY 
  (ENTRYADDITIONALFIELDID, COMPANYID);
ALTER TABLE SYS_ENTRYADDITIONALFIELD ADD CONSTRAINT SYS_ADDFIELD_ENTRYADDFIELD 
  FOREIGN KEY (ADDITIONALFIELDID, COMPANYID) REFERENCES SYS_ADDITIONALFIELD (ADDITIONALFIELDID, COMPANYID);
CREATE INDEX SYS_ENTRYADDITIONALFIELD_OBJPK ON SYS_ENTRYADDITIONALFIELD (OBJECTPK, COMPANYID);
CREATE INDEX SYS_ENTRYADDITIONALFIELD_NAME ON SYS_ENTRYADDITIONALFIELD (OBJECTPK, COMPANYID, NAME);
CREATE INDEX SYS_ENTRYADDITIONALFIELD_FLDID ON SYS_ENTRYADDITIONALFIELD (OBJECTPK, COMPANYID, ADDITIONALFIELDID);

CREATE TABLE SYS_ENTRYADDITIONALFIELDLOB(ENTRYADDITIONALFIELDID NUMBER(38) NOT NULL,
  COMPANYID NUMBER(38) NOT NULL, OBJECTVALUE BLOB);
ALTER TABLE SYS_ENTRYADDITIONALFIELDLOB ADD CONSTRAINT SYS_ENTRYADDITIONALFIELDLOB_PK PRIMARY KEY 
  (ENTRYADDITIONALFIELDID, COMPANYID);
ALTER TABLE SYS_ENTRYADDITIONALFIELDLOB ADD CONSTRAINT SYS_ENTRYADDFIELD_LOB FOREIGN KEY 
  (ENTRYADDITIONALFIELDID, COMPANYID) REFERENCES SYS_ENTRYADDITIONALFIELD (ENTRYADDITIONALFIELDID, COMPANYID)
  ON DELETE CASCADE;

