alter table PLG_BUDGETRESHEADER add
(
  ISUPLOADEDTODIAVGEIA  varchar2(1) default '0' not null,
  DIAVGIAUPLOADDATE date,
  DIAVGIADOCUMENTURL varchar2(50),
  CANCELPROTOCOLNO varchar2(20),
  CANCELPROTOCOLDATE date,
  ISCANCELUPLOADEDTODIAVGIA  varchar2(1) default '0' not null,
  CANCELDIAVGIAUPLOADDATE date,
  CANCELDIAVGIADOCUMENTURL varchar2(50)
);

alter table PLG_BUDGETRESSTATUSLOG add
(
  ISUPLOADEDTODIAVGEIA  varchar2(1) default '0' not null,
  DIAVGIAUPLOADDATE date,
  PROTOCOLNO varchar2(20),
  PROTOCOLDATE date,
  DIAVGIANO varchar2(20),
  DIAVGIADOCUMENTURL varchar2(50),
  DIAVGIARESPONSE CLOB
);