alter table PBL_VISITCOVEREXCLUSIONS add (PERCCOVERINDICATOR NUMBER(38));
alter table PBL_CONTRACTDETAIL add (PERCCOVERINDICATOR NUMBER(38));
alter table PBL_CHARGECOVER add (PERCCOVERINDICATOR NUMBER(38));

alter table PBL_VISITCOVEREXCLUSIONS add (EXEMPTION FLOAT(126));
alter table PBL_CONTRACTDETAIL add (EXEMPTION FLOAT(126));
alter table PBL_CHARGECOVER add (EXEMPTIONVALUECOVER FLOAT(126));

