alter table FIN_EVENTTYPE add SHOWDEBITFINCOSTCENTER VARCHAR2(1);
alter table FIN_EVENTTYPE add SHOWCREDITFINCOSTCENTER VARCHAR2(1);

UPDATE FIN_EVENTTYPE SET SHOWCREDITFINCOSTCENTER = '0', SHOWDEBITFINCOSTCENTER = '0';
COMMIT;

alter table FIN_EVENTTYPE modify SHOWDEBITFINCOSTCENTER not null;
alter table FIN_EVENTTYPE modify SHOWCREDITFINCOSTCENTER not null;