--DELETE ALL ROWS FROM SYS_PHONE WHERE FINTRANSPARTYID NOT EXISTS IN FIN_TRANSPARTY TABLE
DELETE FROM SYS_PHONE TB_PHONE
       WHERE TB_PHONE.FINTRANSPARTYID IS NOT NULL
         AND NOT EXISTS (SELECT TB_FINPARTY.FINTRANSPARTYID
                           FROM FIN_TRANSPARTY TB_FINPARTY
                          WHERE TB_PHONE.FINTRANSPARTYID = TB_FINPARTY.FINTRANSPARTYID
                            AND TB_PHONE.COMPANYID = TB_FINPARTY.COMPANYID
                            AND TB_PHONE.FYEARID = TB_FINPARTY.FYEARID)
         AND TB_PHONE.TAXBRANCHID IS NULL;

--NULLIFY FINTRANSPARTYID 4 SYS_PHONE WHERE FINTRANSPARTYID NOT EXISTS IN FIN_TRANSPARTY & TAXBRANCHID NOT NULL
--BECAUSE THE RELATIONSHIP OF SYS_PHONE --> FIN_TAXBRANCH DOES NOT ALLOW US 2 DELETE THESE ROWS
UPDATE SYS_PHONE TB_PHONE
  SET FINTRANSPARTYID = NULL
  WHERE TB_PHONE.FINTRANSPARTYID IS NOT NULL
    AND NOT EXISTS (SELECT TB_FINPARTY.FINTRANSPARTYID
                      FROM FIN_TRANSPARTY TB_FINPARTY
                     WHERE TB_PHONE.FINTRANSPARTYID = TB_FINPARTY.FINTRANSPARTYID
                       AND TB_PHONE.COMPANYID = TB_FINPARTY.COMPANYID
                       AND TB_PHONE.FYEARID = TB_FINPARTY.FYEARID)
    AND TB_PHONE.TAXBRANCHID IS NOT NULL;
COMMIT;

ALTER TABLE SYS_PHONE
  DROP CONSTRAINT FK_SYS_PHON_TRANSPART_FIN_TRAN;

ALTER TABLE SYS_PHONE
  ADD CONSTRAINT FK_SYS_PHON_TRANSPART_FIN_TRAN FOREIGN KEY (FINTRANSPARTYID,COMPANYID,FYEARID)
  REFERENCES FIN_TRANSPARTY (FINTRANSPARTYID,COMPANYID,FYEARID) ON DELETE CASCADE;


--DELETE ALL ROWS FROM SYS_ADDRESS WHERE FINTRANSPARTYID NOT EXISTS IN FIN_TRANSPARTY TABLE
DELETE FROM SYS_ADDRESS TB_ADDRESS
  WHERE TB_ADDRESS.FINTRANSPARTYID IS NOT NULL
    AND NOT EXISTS (SELECT TB_FINPARTY.FINTRANSPARTYID
                      FROM FIN_TRANSPARTY TB_FINPARTY
                     WHERE TB_ADDRESS.FINTRANSPARTYID = TB_FINPARTY.FINTRANSPARTYID
                       AND TB_ADDRESS.COMPANYID = TB_FINPARTY.COMPANYID
                       AND TB_ADDRESS.FYEARID = TB_FINPARTY.FYEARID)
    AND TB_ADDRESS.TAXBRANCHID IS NULL;

--NULLIFY FINTRANSPARTYID 4 SYS_ADDRESS WHERE FINTRANSPARTYID NOT EXISTS IN FIN_TRANSPARTY & TAXBRANCHID NOT NULL
--BECAUSE THE RELATIONSHIP OF SYS_ADDRESS --> FIN_TAXBRANCH DOES NOT ALLOW US 2 DELETE THESE ROWS
UPDATE SYS_ADDRESS TB_ADDRESS
  SET FINTRANSPARTYID = NULL
  WHERE TB_ADDRESS.FINTRANSPARTYID IS NOT NULL
    AND NOT EXISTS (SELECT TB_FINPARTY.FINTRANSPARTYID
                      FROM FIN_TRANSPARTY TB_FINPARTY
                     WHERE TB_ADDRESS.FINTRANSPARTYID = TB_FINPARTY.FINTRANSPARTYID
                       AND TB_ADDRESS.COMPANYID = TB_FINPARTY.COMPANYID
                       AND TB_ADDRESS.FYEARID = TB_FINPARTY.FYEARID)
    AND TB_ADDRESS.TAXBRANCHID IS NOT NULL;
COMMIT;

ALTER TABLE SYS_ADDRESS
  DROP CONSTRAINT FK_SYS_ADDR_TRANSPART_FIN_TRAN;


ALTER TABLE SYS_ADDRESS
  ADD CONSTRAINT FK_SYS_ADDR_TRANSPART_FIN_TRAN FOREIGN KEY (FINTRANSPARTYID,COMPANYID,FYEARID)
  REFERENCES FIN_TRANSPARTY (FINTRANSPARTYID,COMPANYID,FYEARID) ON DELETE CASCADE;

--DELETE ALL ROWS FROM SYS_PHONE WHERE TAXBRANCHID NOT EXISTS IN FIN_TAXBRANCH TABLE
DELETE FROM SYS_PHONE TB_PHONE
  WHERE TB_PHONE.TAXBRANCHID IS NOT NULL
    AND NOT EXISTS
       (SELECT TB_FINBRANCH.TAXBRANCHID
          FROM FIN_TAXBRANCH TB_FINBRANCH
         WHERE TB_PHONE.TAXBRANCHID = TB_FINBRANCH.TAXBRANCHID
           AND TB_PHONE.COMPANYID = TB_FINBRANCH.COMPANYID
           AND TB_PHONE.FYEARID = TB_FINBRANCH.FYEARID)
    AND TB_PHONE.FINTRANSPARTYID IS NULL;


--NULLIFY TAXBRANCHID 4 SYS_PHONE WHERE TAXBRANCHID NOT EXISTS IN FIN_TAXBRANCH & FINTRANSPARTYID NOT NULL
--BECAUSE THE RELATIONSHIP OF SYS_PHONE --> FIN_FINTRANSPARTY DOES NOT ALLOW US 2 DELETE THESE ROWS
UPDATE SYS_PHONE TB_PHONE SET TAXBRANCHID = NULL
  WHERE TB_PHONE.TAXBRANCHID IS NOT NULL
    AND NOT EXISTS
      (SELECT TB_FINBRANCH.TAXBRANCHID
         FROM FIN_TAXBRANCH TB_FINBRANCH
        WHERE TB_PHONE.TAXBRANCHID = TB_FINBRANCH.TAXBRANCHID
          AND TB_PHONE.COMPANYID = TB_FINBRANCH.COMPANYID
          AND TB_PHONE.FYEARID = TB_FINBRANCH.FYEARID)
    AND TB_PHONE.FINTRANSPARTYID IS NOT NULL;
COMMIT;

ALTER TABLE SYS_PHONE
  DROP CONSTRAINT FK_SYS_PHON_FIN_TAXBR_FIN_TAXB;

ALTER TABLE SYS_PHONE
  ADD CONSTRAINT FK_SYS_PHON_FIN_TAXBR_FIN_TAXB FOREIGN KEY (TAXBRANCHID,COMPANYID,FYEARID)
  REFERENCES FIN_TAXBRANCH (TAXBRANCHID,COMPANYID,FYEARID) ON DELETE CASCADE;


--DELETE ALL ROWS FROM SYS_ADDRESS WHERE TAXBRANCHID NOT EXISTS IN FIN_TAXBRANCH TABLE
DELETE FROM SYS_ADDRESS TB_ADDRESS
  WHERE TB_ADDRESS.TAXBRANCHID IS NOT NULL
    AND NOT EXISTS
      (SELECT TB_FINBRANCH.TAXBRANCHID
         FROM FIN_TAXBRANCH TB_FINBRANCH
        WHERE TB_ADDRESS.TAXBRANCHID = TB_FINBRANCH.TAXBRANCHID
          AND TB_ADDRESS.COMPANYID = TB_FINBRANCH.COMPANYID
          AND TB_ADDRESS.FYEARID = TB_FINBRANCH.FYEARID)
    AND TB_ADDRESS.FINTRANSPARTYID IS NULL;

--NULLIFY TAXBRANCHID 4 SYS_ADDRESSS WHERE TAXBRANCHID NOT EXISTS IN FIN_TAXBRANCH & FINTRANSPARTYID NOT NULL
--BECAUSE THE RELATIONSHIP OF SYS_ADDRESS --> FIN_FINTRANSPARTY DOES NOT ALLOW US 2 DELETE THESE ROWS

--THETOUME NULL WS TAXBRANCHID GIA OSES EGGRAFES TOY SYS_ADDRESS EXOUN TAXBRANCHID TO OPOIO DEN UPARXEI STON FIN_TAXBRANCH KAI EXOUN FINTRANSPARTYID
UPDATE SYS_ADDRESS TB_ADDRESS SET TAXBRANCHID = NULL
  WHERE TB_ADDRESS.TAXBRANCHID IS NOT NULL
    AND NOT EXISTS
      (SELECT TB_FINBRANCH.TAXBRANCHID
         FROM FIN_TAXBRANCH TB_FINBRANCH
        WHERE TB_ADDRESS.TAXBRANCHID = TB_FINBRANCH.TAXBRANCHID
          AND TB_ADDRESS.COMPANYID = TB_FINBRANCH.COMPANYID
          AND TB_ADDRESS.FYEARID = TB_FINBRANCH.FYEARID)
    AND TB_ADDRESS.FINTRANSPARTYID IS NOT NULL;
COMMIT;
             
ALTER TABLE SYS_ADDRESS
  DROP CONSTRAINT FK_SYS_ADDR_FIN_TAXBR_FIN_TAXB;


ALTER TABLE SYS_ADDRESS
  ADD CONSTRAINT FK_SYS_ADDR_FIN_TAXBR_FIN_TAXB FOREIGN KEY (TAXBRANCHID,COMPANYID,FYEARID)
  REFERENCES FIN_TAXBRANCH (TAXBRANCHID,COMPANYID,FYEARID) ON DELETE CASCADE;
