alter table PBL_VISITCOVERDETAIL
  add constraint FK_VISIT_VISITCOVERDT foreign key (VISITID, COMPANYID, FYEARID)
  references pta_visit (VISITID, COMPANYID, FYEARID);

create index FK_VISIT_VISITCOVERDT on PBL_VISITCOVERDETAIL (VISITID, COMPANYID, FYEARID);
