create sequence BANKACCOUNT_OBJ_USERS_SEQ
minvalue 0
maxvalue 9999999999
start with 0
INCREMENT BY 1 NOCACHE;

INSERT INTO SYS_OBJECTUSERS(COMPANYID,ISPUBLICTOALLUSERS,OBJECTID,OBJECTPK,OBJECTUSERSID)
SELECT FIN_BANKACCOUNT.COMPANYID, '1','FIN_BANKACCOUNT',
  'FIN_BANKACCOUNT.BANKACCOUNTID='|| FIN_BANKACCOUNT.BANKACCOUNTID ||
  '|FIN_BANKACCOUNT.COMPANYID=' ||FIN_BANKACCOUNT.COMPANYID ||'|FIN_BANKACCOUNT.FYEARID=' || FIN_BANKACCOUNT.FYEARID,
BANKACCOUNT_OBJ_USERS_SEQ.NEXTVAL+(SELECT A.COUNTER FROM SYS_SEQUENCE A WHERE A.OBJECTID = 'SYS_OBJECTUSERS')
  FROM FIN_BANKACCOUNT
	WHERE FIN_BANKACCOUNT.FYEARID = 2009;

UPDATE SYS_SEQUENCE SET COUNTER =
  (SELECT MAX(OBJECTUSERSID)+1 FROM SYS_OBJECTUSERS
     WHERE OBJECTID = 'FIN_BANKACCOUNT')
WHERE OBJECTID = 'SYS_OBJECTUSERS';
COMMIT;

DROP sequence BANKACCOUNT_OBJ_USERS_SEQ;