alter table PBL_VISITCOVERDETAIL add ISSUGGESTINGPRICELIST varchar2(1);
UPDATE PBL_VISITCOVERDETAIL SET ISSUGGESTINGPRICELIST = '0';
COMMIT;
alter table PBL_VISITCOVERDETAIL modify ISSUGGESTINGPRICELIST not null;
