CREATE TABLE PBL_CARDPARAMETERS(
  FINITEMID NUMBER(38) NOT NULL,
  COMPANYID NUMBER(38) NOT NULL,
  FYEARID NUMBER(38) NOT NULL
);

ALTER TABLE PBL_CARDPARAMETERS ADD CONSTRAINT PBL_CARDPARAMETERS_PK
  PRIMARY KEY (COMPANYID, FYEARID);
ALTER TABLE PBL_CARDPARAMETERS ADD CONSTRAINT 
  FIN_ITEM_PBL_CARDPARAMETERS_FK FOREIGN KEY (FINITEMID, COMPANYID, FYEARID) REFERENCES 
  FIN_ITEM (FINITEMID, COMPANYID, FYEARID);

CREATE TABLE PBL_CARDCONTRACT(
  CARDCONTRACTID NUMBER(38) NOT NULL,
  COMPANYID NUMBER(38) NOT NULL,
  MNEMONIC VARCHAR2(20) NOT NULL,
  DESCR VARCHAR2(50) NOT NULL,
  VALIDSINCEDATE DATE NOT NULL,
  VALIDTILLDATE DATE,
  FINTRANSPARTYID NUMBER(38),
  FYEARID NUMBER(38) NOT NULL,
  CONTRACTHEADERID NUMBER(38)  NOT NULL,
  ISACTIVE VARCHAR2(20) NOT NULL
);

ALTER TABLE PBL_CARDCONTRACT ADD CONSTRAINT PBL_CARDCONTRACT_PK PRIMARY KEY (CARDCONTRACTID, COMPANYID);

ALTER TABLE PBL_CARDCONTRACT ADD CONSTRAINT TRANSPARTY_PBL_CARDCONTRACT_FK FOREIGN KEY
   (FINTRANSPARTYID, COMPANYID, FYEARID) REFERENCES FIN_TRANSPARTY
   (FINTRANSPARTYID, COMPANYID, FYEARID);
   
ALTER TABLE PBL_CARDCONTRACT ADD CONSTRAINT CONTRACTHD_PBL_CARDCONTRACT_FK FOREIGN KEY
   (CONTRACTHEADERID, COMPANYID, FYEARID) REFERENCES PBL_CONTRACTHEADER
   (CONTRACTHEADERID, COMPANYID, FYEARID);

CREATE TABLE PBL_CARD(  
  CARDID NUMBER(38) NOT NULL,
  COMPANYID NUMBER(38) NOT NULL,
  FYEARID NUMBER(38) NOT NULL,
  INOUTPATIENT NUMBER(38),
  CARDNO VARCHAR2(20) NOT NULL,
  CARDCONTRACTID NUMBER(38),
  FINTRANSPARTYID NUMBER(38),
  CONTRACTHEADERID NUMBER(38),
  APPLICATIONDATE DATE,
  ISSUEDATE DATE  NOT NULL,
  VALIDSINCEDATE DATE NOT NULL,
  VALIDTILLDATE DATE,
  ISACTIVE VARCHAR2(1) NOT NULL,
  MARKETINGINDICATOR NUMBER(38),
  PURCHASEINDICATOR NUMBER(38),
  ISCARDISSUED VARCHAR2(1) NOT NULL,
  ISCANCELED VARCHAR2(1) NOT NULL,
  CANCELDATE DATE,
  CANCELREASON VARCHAR2(100),
  COMMENTS VARCHAR2(100)
   );

ALTER TABLE PBL_CARD ADD CONSTRAINT PBL_CARD_PK PRIMARY KEY (CARDID, COMPANYID);

ALTER TABLE PBL_CARD ADD CONSTRAINT PBL_CARDCONTRACT_PBL_CARD_FK FOREIGN KEY (CARDCONTRACTID, COMPANYID)
REFERENCES PBL_CARDCONTRACT(CARDCONTRACTID, COMPANYID);

ALTER TABLE PBL_CARD ADD CONSTRAINT FIN_TRANSPARTY_PBL_CARD_FK FOREIGN KEY (FINTRANSPARTYID, COMPANYID, FYEARID) 
  REFERENCES FIN_TRANSPARTY (FINTRANSPARTYID, COMPANYID, FYEARID);
  
ALTER TABLE PBL_CARD ADD CONSTRAINT PBL_CONTRACTHD_PBL_CARD_FK FOREIGN KEY
   (CONTRACTHEADERID, COMPANYID, FYEARID) REFERENCES PBL_CONTRACTHEADER
   (CONTRACTHEADERID, COMPANYID, FYEARID);


CREATE TABLE PBL_CARDHOLDER(
  CARDHOLDERID NUMBER(38) NOT NULL,
  COMPANYID NUMBER(38) NOT NULL,
  FYEARID NUMBER(38) NOT NULL,
  CARDID NUMBER(38) NOT NULL,
  CARDMEMBERID NUMBER(38) NOT NULL,
  LASTNAME VARCHAR2(50) NOT NULL, 
  FIRSTNAME VARCHAR2(50) NOT NULL,
  FATHERFIRSTNAME VARCHAR2(50),
  FATHERLASTNAME VARCHAR2(50),
  MOTHERFIRSTNAME VARCHAR2(50),
  MOTHERLASTNAME VARCHAR2(50),
  IDNUMBER VARCHAR2(15),
  IDDATE DATE,
  IDISSUER VARCHAR2(40),
  PASSPORTNUMBER VARCHAR2(40),
  PASSPORTDATE DATE,
  PASSPORTCOUNTRYID NUMBER(38),
  BIRTHDATE DATE,
  TAXREGISTRATIONNO VARCHAR2(10),
  TAXBRANCHID NUMBER(38),
  GENDERID NUMBER(38),
  PARTNERLASTNAME VARCHAR2(50),
  PARTNERFIRSTNAME VARCHAR2(50),
  RELATIONSHIPINDICATOR NUMBER(38),
  MARITALSTATUSID NUMBER(38),
  PATIENTID NUMBER(38));

ALTER TABLE PBL_CARDHOLDER ADD CONSTRAINT PBL_CARDHOLDER_PK PRIMARY KEY (CARDHOLDERID, COMPANYID);

ALTER TABLE PBL_CARDHOLDER ADD CONSTRAINT CARD_PBL_CARDHOLDER_FK FOREIGN KEY (CARDID, COMPANYID)
REFERENCES PBL_CARD(CARDID, COMPANYID);

ALTER TABLE PBL_CARDHOLDER ADD CONSTRAINT TAXBRANCH_PBL_CARDHOLDER_FK FOREIGN KEY (TAXBRANCHID, COMPANYID, FYEARID) 
  REFERENCES FIN_TAXBRANCH (TAXBRANCHID, COMPANYID, FYEARID);

ALTER TABLE PBL_CARDHOLDER ADD CONSTRAINT PTA_PATIENT_PBL_CARDHOLDER_FK FOREIGN KEY (PATIENTID, COMPANYID) 
   REFERENCES PTA_PATIENT (PATIENTID, COMPANYID);
  

ALTER TABLE FIN_TRANSHEADER ADD (CARDID NUMBER(38), CARDCONTRACTID NUMBER(38));
ALTER TABLE FIN_TRANSHEADER ADD CONSTRAINT PBL_CARD_FIN_TRANSHEADER_FK FOREIGN KEY
  (CARDID, COMPANYID)REFERENCES PBL_CARD
  (CARDID, COMPANYID);
ALTER TABLE FIN_TRANSHEADER ADD CONSTRAINT 
  CARDCONTRACT_FIN_TRANSHD_FK FOREIGN KEY (CARDCONTRACTID, COMPANYID)
  REFERENCES PBL_CARDCONTRACT(CARDCONTRACTID, COMPANYID);

ALTER TABLE PTA_VISIT ADD (CARDID NUMBER(38), CARDHOLDERID NUMBER(38));
ALTER TABLE PTA_VISIT ADD CONSTRAINT PBL_CARD_PTA_VISIT_FK FOREIGN KEY (CARDID, COMPANYID)
  REFERENCES PBL_CARD(CARDID, COMPANYID);
  
ALTER TABLE PTA_VISIT ADD CONSTRAINT PBL_CARDHOLDER_PTA_VISIT_FK FOREIGN KEY(CARDHOLDERID, COMPANYID)
  REFERENCES PBL_CARDHOLDER(CARDHOLDERID, COMPANYID);
  
ALTER TABLE PBL_VISITCOVERDETAIL ADD (CARDID NUMBER(38), CARDHOLDERID NUMBER(38));

ALTER TABLE PBL_VISITCOVERDETAIL ADD CONSTRAINT CARD_PBL_VISITCOVERDT_FK FOREIGN KEY (CARDID, COMPANYID)
  REFERENCES PBL_CARD(CARDID, COMPANYID);
  
ALTER TABLE PBL_VISITCOVERDETAIL ADD CONSTRAINT CARDHOLDER_PBL_VISITCOVERDT_FK FOREIGN KEY (CARDHOLDERID, COMPANYID)
  REFERENCES PBL_CARDHOLDER(CARDHOLDERID, COMPANYID);

alter table SYS_PHONE add CARDHOLDERID number(38);
alter table SYS_PHONE
  add constraint SYS_PHONE_CARDHOLDER_FK foreign key (cardholderid,companyid)
  references PBL_CARDHOLDER (cardholderid,companyid) on delete cascade;

alter table SYS_ADDRESS add CARDHOLDERID number(38);
alter table SYS_ADDRESS
  add constraint SYS_ADDRESS_CARDHOLDER_FK foreign key (cardholderid,companyid)
  references PBL_CARDHOLDER (cardholderid,companyid) on delete cascade;
