ALTER TABLE FIN_ITEM ADD VATIDOUTPATIENTS NUMBER(38);
UPDATE FIN_ITEM SET VATIDOUTPATIENTS = VATID;
COMMIT;
ALTER TABLE FIN_ITEM MODIFY VATIDOUTPATIENTS NOT NULL;
ALTER TABLE FIN_ITEM ADD CONSTRAINT
  RTP_VAT_FIN_ITEM_OUTP_FK FOREIGN KEY (VATIDOUTPATIENTS, COMPANYID, FYEARID)
   REFERENCES ERP_VAT(VATID,COMPANYID,FYEARID);