ALTER TABLE RSC_RESOURCEALLOCATION ADD DOCTORID NUMBER(38);
ALTER TABLE RSC_RESOURCEALLOCATION ADD CONSTRAINT PTA_DOCTOR_RSCALLOCATION_FK
  FOREIGN KEY (DOCTORID, COMPANYID, FYEARID) REFERENCES PTA_DOCTOR(DOCTORID, COMPANYID, FYEARID);
CREATE INDEX PTA_DOCTOR_RSCALLOCATION_FK ON RSC_RESOURCEALLOCATION (DOCTORID, COMPANYID, FYEARID);  