ALTER TABLE PBL_PARAMETERS ADD (COSTCENTERPOLICYINPATIENTS NUMBER(38), COSTCENTERPOLICYOUTPATIENTS NUMBER(38));
UPDATE PBL_PARAMETERS SET COSTCENTERPOLICYINPATIENTS = 1, COSTCENTERPOLICYOUTPATIENTS = 2;
COMMIT;
  