alter table PTA_PATIENTDEBTCOMMENT add COMMENTTYPEINDICATOR number(38);

UPDATE PTA_PATIENTDEBTCOMMENT SET COMMENTTYPEINDICATOR = 2
COMMIT;

alter table PTA_PATIENTDEBTCOMMENT modify COMMENTTYPEINDICATOR not null;

