alter table RSC_RESOURCEALLOCATION add PROTOCOLINDICATOR number(38);
alter table RSC_RESOURCEALLOCATION add PROTOCOLCOMMENTS varchar2(100);

--OBJECT USERS 2 RESOURCEGROUP
create sequence RESOURCEGROUP_OBJ_USERS_SEQ
minvalue 0
maxvalue 9999999999
start with 0
INCREMENT BY 1 NOCACHE;

INSERT INTO SYS_OBJECTUSERS(COMPANYID,ISPUBLICTOALLUSERS,OBJECTID,OBJECTPK,OBJECTUSERSID)
SELECT RSC_RESOURCEGROUP.COMPANYID, '1','RSC_RESOURCEGROUP',
  'RSC_RESOURCEGROUP.COMPANYID=' ||RSC_RESOURCEGROUP.COMPANYID||
  '|RSC_RESOURCEGROUP.FYEARID=' ||RSC_RESOURCEGROUP.FYEARID||
  '|RSC_RESOURCEGROUP.RESOURCEGROUPID='|| RSC_RESOURCEGROUP.RESOURCEGROUPID,
 RESOURCEGROUP_OBJ_USERS_SEQ.NEXTVAL+(SELECT A.COUNTER FROM SYS_SEQUENCE A WHERE A.OBJECTID = 'SYS_OBJECTUSERS')
  FROM RSC_RESOURCEGROUP;

UPDATE SYS_SEQUENCE SET COUNTER =
  (SELECT MAX(OBJECTUSERSID)+1 FROM SYS_OBJECTUSERS
     WHERE OBJECTID = 'RSC_RESOURCEGROUP')
WHERE OBJECTID = 'SYS_OBJECTUSERS';
COMMIT;

DROP sequence RESOURCEGROUP_OBJ_USERS_SEQ;
