ALTER TABLE MED_MEDICALSTATUS ADD ISNOEDIT VARCHAR2(1);
UPDATE MED_MEDICALSTATUS SET ISNOEDIT = '0';
COMMIT;
ALTER TABLE MED_MEDICALSTATUS MODIFY ISNOEDIT NOT NULL;

ALTER TABLE MED_SERVICESTATUSLOG ADD COMMENTS VARCHAR2(50);
ALTER TABLE MED_SERVICE MODIFY PROTOCOLNO VARCHAR2(40); 