alter table PTA_PARAMETERS add CHKEXTENSIONEXPIRY varchar2(1);
alter table PTA_PARAMETERS add EXTENSIONEXPIRYTHRESHOLD number(38);

UPDATE PTA_PARAMETERS SET CHKEXTENSIONEXPIRY = '0';
COMMIT;

alter table PTA_PARAMETERS modify CHKEXTENSIONEXPIRY not null;
