ALTER TABLE INV_TRANSHEADER
  ADD CONSTRAINT BUYINVTRANSHEADERID_FK FOREIGN KEY (BUYINVTRANSHEADERID, COMPANYID, FYEARID)
  REFERENCES INV_TRANSHEADER (INVTRANSHEADERID, COMPANYID, FYEARID);
ALTER TABLE INV_TRANSHEADER ADD (ORDERINVSTOREID NUMBER(38), ORDERSTOREDATE DATE, ORDERSTORENUM VARCHAR2(20));