alter table AST_ASSETPART add ASSETPARTID number(38);
UPDATE AST_ASSETPART SET ASSETPARTID = INVITEMID;
COMMIT;

alter table AST_ASSETPART modify ASSETPARTID not null;

alter table AST_ASSETPART
  drop constraint AST_ASSETPART_PK cascade;

drop index AST_ASSETPART_PK;

alter table AST_ASSETPART
  add constraint AST_ASSETPART_PK primary key (ASSETPARTID, COMPANYID, FYEARID);


alter table AST_ASSETPARTLINK
  drop constraint ASSETPART_ASSETPARTLINK_FK;

alter table AST_ASSETPARTLINK
  add constraint ASSETPART_ASSETPARTLINK_FK foreign key (ASSETPARTID, COMPANYID, FYEARID)
  references ast_assetPART (ASSETPARTID, COMPANYID, FYEARID);

create index ASSETPART_ASSETPARTLINK_FK on AST_ASSETPARTLINK (assetpartid, companyid, fyearid);

alter table FIN_TRANSDETAIL add ASSETPARTINVITEMID number(38);

UPDATE FIN_TRANSDETAIL SET ASSETPARTINVITEMID = ASSETPARTID;
COMMIT;

INSERT INTO SYS_SEQUENCE (COMPANYID,FYEARID,OBJECTID,COUNTER,OBJECTDESCRIPTION)
  SELECT 1,0,'AST_ASSETPART', MAX(ASSETPARTID)+1, 'ASSET PARTS' FROM AST_ASSETPART;
COMMIT;

