alter table PBL_PRICELISTHEADER add (INOUTPATIENTINDICATOR NUMBER(38));

alter table PBL_CONTRACTHEADER add (INOUTPATIENTINDICATOR NUMBER(38));

alter table PBL_INSURANCESCHEMEHEADER add (INOUTPATIENTINDICATOR NUMBER(38));
