alter table FIN_EVENTTYPE add INVOICEKINDINDICATOR number(38);

UPDATE FIN_EVENTTYPE SET INVOICEKINDINDICATOR = 3
  WHERE EVENTTYPEINDICATOR IN (3,4,5,6);

UPDATE FIN_EVENTTYPE SET INVOICEKINDINDICATOR = 4
  WHERE EVENTTYPEINDICATOR NOT IN (3,4,5,6);
COMMIT;

alter table FIN_TRANSPARTY add ISISSUINGREQINVOICE varchar2(1);

UPDATE FIN_TRANSPARTY SET ISISSUINGREQINVOICE = '0';
COMMIT;

alter table FIN_TRANSPARTY modify ISISSUINGREQINVOICE not null;

