INSERT INTO SYS_OBJECT(OBJECTID, OBJECTTYPE, DESCR, YEARMIGRATIONORDER, YEARMIGRATIONACTION, ISMIGRATED)
  VALUES ('PBL_CHARGEPACKAGEEXCLUDEDITEM',  1,  'PBL_CHARGEPACKAGEEXCLUDEDITEM', 300, 1, '1');
INSERT INTO SYS_OBJECT(OBJECTID, OBJECTTYPE, DESCR, YEARMIGRATIONORDER, YEARMIGRATIONACTION, ISMIGRATED)
  VALUES ('INV_ALTERNATIVEDRUG',  1,  'INV_ALTERNATIVEDRUG', 301, 1, '1') ;
INSERT INTO SYS_OBJECT(OBJECTID, OBJECTTYPE, DESCR, YEARMIGRATIONORDER, YEARMIGRATIONACTION, ISMIGRATED)
  VALUES ('INV_STOREAPPROVEUSERS',  1,  'INV_STOREAPPROVEUSERS', 302, 1, '1') ;
