ALTER TABLE MED_PARAMETERS ADD DEFAULTVATSALESIDOUTPATIENTS NUMBER(38);
UPDATE MED_PARAMETERS SET DEFAULTVATSALESIDOUTPATIENTS =  DEFAULTVATSALESID;
COMMIT;
ALTER TABLE MED_PARAMETERS MODIFY DEFAULTVATSALESIDOUTPATIENTS NOT NULL;
ALTER TABLE MED_PARAMETERS ADD CONSTRAINT ERP_VAT_MED_PAR_VATSALUTP_FK
  FOREIGN KEY(DEFAULTVATSALESIDOUTPATIENTS, COMPANYID, FYEARID)
  REFERENCES ERP_VAT(VATID, COMPANYID, FYEARID);
