alter table FIN_ITEM
  add constraint FK_FIN_ITEM_PTA_FACILITY foreign key (FACILITYEXECID, COMPANYID, FYEARID)
  references pta_facility (FACILITYID, COMPANYID, FYEARID);
create index FK_FIN_ITEM_PTA_FACILITY on FIN_ITEM (facilityexecid, companyid, fyearid);

--IN CASE OF NON-EXISTING VISITCOVEERDETAILS
DELETE FROM SYS_ADDRESS
  WHERE NOT EXISTS
	  (SELECT * FROM PBL_VISITCOVERDETAIL
      WHERE PBL_VISITCOVERDETAIL.VISITCOVERDETAILID = SYS_ADDRESS.VISITCOVERDETAILID
			  AND PBL_VISITCOVERDETAIL.COMPANYID = SYS_ADDRESS.COMPANYID
				AND PBL_VISITCOVERDETAIL.FYEARID = SYS_ADDRESS.FYEARID)
		AND SYS_ADDRESS.VISITCOVERDETAILID IS NOT NULL
		AND SYS_ADDRESS.FINTRANSPARTYID IS NULL AND SYS_ADDRESS.TAXBRANCHID IS NULL;
COMMIT;

alter table SYS_ADDRESS
  add constraint FK_SYS_ADDRESS_VISITCOVERDT foreign key (VISITCOVERDETAILID, COMPANYID, FYEARID)
  references pbl_visitcoverdetail (VISITCOVERDETAILID, COMPANYID, FYEARID) on delete cascade;

create index FK_SYS_ADDRESS_VISITCOVERDT on SYS_ADDRESS (visitcoverdetailid, companyid, fyearid);
