ALTER TABLE INV_PARAMETERS ADD DEFAULTVATSALESIDOUTPATIENTS NUMBER(38);
UPDATE INV_PARAMETERS SET DEFAULTVATSALESIDOUTPATIENTS =  DEFAULTVATSALESID;
COMMIT;
ALTER TABLE INV_PARAMETERS MODIFY DEFAULTVATSALESIDOUTPATIENTS NOT NULL;
ALTER TABLE INV_PARAMETERS ADD CONSTRAINT ERP_VAT_INV_PAR_VATSALUTP_FK
  FOREIGN KEY(DEFAULTVATSALESIDOUTPATIENTS, COMPANYID, FYEARID)
  REFERENCES ERP_VAT(VATID, COMPANYID, FYEARID);
