CREATE TABLE INV_ITEMSTOREACCESS
(
  INVITEMID      NUMBER(38) NOT NULL,
  INVSTOREID     NUMBER(38) NOT NULL,
  COMPANYID      NUMBER(38) NOT NULL,
  FYEARID        NUMBER(38) NOT NULL );

ALTER TABLE INV_ITEMSTOREACCESS
  ADD CONSTRAINT INV_ITEMSTOREACCESS_PK PRIMARY KEY (INVITEMID, INVSTOREID, COMPANYID, FYEARID);

ALTER TABLE INV_ITEMSTOREACCESS
  ADD CONSTRAINT INV_STORE_ITEMSTOREACCESS_FK FOREIGN KEY (INVSTOREID, COMPANYID, FYEARID)
  REFERENCES INV_STORE (INVSTOREID, COMPANYID, FYEARID) ON DELETE CASCADE;

ALTER TABLE INV_ITEMSTOREACCESS
  ADD CONSTRAINT INV_ITEM_ITEMSTOREACCESS_FK FOREIGN KEY (INVITEMID, COMPANYID, FYEARID)
  REFERENCES INV_ITEM (INVITEMID, COMPANYID, FYEARID) ON DELETE CASCADE;

CREATE INDEX INV_STORE_ITEMSTOREACCESS_FK ON INV_ITEMSTOREACCESS (INVSTOREID, COMPANYID, FYEARID);
CREATE INDEX INV_ITEM_ITEMSTOREACCESS_FK ON INV_ITEMSTOREACCESS (INVITEMID, COMPANYID, FYEARID);

ALTER TABLE INV_ITEM ADD ISPUBLICTOALLSTORES VARCHAR2(1);
UPDATE INV_ITEM SET ISPUBLICTOALLSTORES = '1';
COMMIT;
ALTER TABLE INV_ITEM MODIFY ISPUBLICTOALLSTORES NOT NULL;