CREATE TABLE MED_PRESCRIPTION(
  PRESCRIPTIONID NUMBER(38) NOT NULL,
  COMPANYID NUMBER(38) NOT NULL,
  FYEARID NUMBER(38) NOT NULL,
  ORDERHEADERID NUMBER(38) NOT NULL,
  INTERNALEVENTNO VARCHAR2(10) NOT NULL,
  MEDEVENTTYPEID  NUMBER(38),
  VISITID NUMBER(38),
  ORDERDATE DATE NOT NULL,
  SCHEDULEDATE DATE,
  ORDERSTATUS NUMBER(38) NOT NULL,
  LINENUM NUMBER(38) NOT NULL,
  SUBSTANCEID NUMBER(38),
  SUBSTANCEQUA FLOAT(126),
  SUBSTANCEUNITOFMEASURE VARCHAR2(20),
  DIAGNOSISGROUPINGID NUMBER(38),
  DIAGNOSISCODEID VARCHAR2(40),
  COMMENTS VARCHAR2(100)
);
ALTER TABLE MED_PRESCRIPTION
  ADD CONSTRAINT MED_PRESCRIPTION_PK
    PRIMARY KEY(PRESCRIPTIONID, COMPANYID, FYEARID);
ALTER TABLE MED_PRESCRIPTION
  ADD CONSTRAINT INV_SUBSTANCE_PRESCRIPTION_FK
    FOREIGN KEY(SUBSTANCEID, COMPANYID)
    REFERENCES INV_SUBSTANCE(SUBSTANCEID, COMPANYID);
ALTER TABLE MED_PRESCRIPTION
  ADD CONSTRAINT MED_ORDERHD_PRESCRIPTION_FK
    FOREIGN KEY(ORDERHEADERID, COMPANYID, FYEARID)
    REFERENCES MED_ORDERHEADER(ORDERHEADERID, COMPANYID, FYEARID);
ALTER TABLE MED_PRESCRIPTION
  ADD CONSTRAINT PTA_VISIT_PRESCRIPTION_FK
    FOREIGN KEY(VISITID, COMPANYID, FYEARID)
    REFERENCES PTA_VISIT(VISITID, COMPANYID, FYEARID);
ALTER TABLE MED_PRESCRIPTION
  ADD CONSTRAINT PTA_DIAGNOSISCD_PRESCR_FK
    FOREIGN KEY(DIAGNOSISGROUPINGID, DIAGNOSISCODEID, COMPANYID)
    REFERENCES PTA_DIAGNOSISCODE(DIAGNOSISGROUPINGID, DIAGNOSISCODEID, COMPANYID);

CREATE INDEX MED_ORDERHD_PRESCRIPTION_FK ON MED_PRESCRIPTION (ORDERHEADERID, COMPANYID, FYEARID);
CREATE INDEX PTA_VISIT_PRESCRIPTION_FK ON MED_PRESCRIPTION (VISITID, COMPANYID, FYEARID);

ALTER TABLE MED_ORDERDETAIL ADD(
  PRESCRIPTIONID NUMBER(38),
  ISCURRENTORDERDETAIL VARCHAR2(1) DEFAULT '1' NOT NULL
);
ALTER TABLE MED_ORDERDETAIL
  ADD CONSTRAINT MED_PRESCRIPTION_ORDERDT_FK
  FOREIGN KEY (PRESCRIPTIONID, COMPANYID, FYEARID)
  REFERENCES MED_PRESCRIPTION(PRESCRIPTIONID, COMPANYID, FYEARID)
  ON DELETE CASCADE;

ALTER TABLE MED_ORDERRECURRENCE ADD(
  PRESCRIPTIONID NUMBER(38),
  STARTTIME TIMESTAMP(6),
  ENDTIME TIMESTAMP(6),
  ADDHOCCONDITION VARCHAR2(40)
);
ALTER TABLE MED_ORDERRECURRENCE
  ADD CONSTRAINT MED_PRESCRIPTION_RECURRENCE_FK
  FOREIGN KEY (PRESCRIPTIONID, COMPANYID, FYEARID)
  REFERENCES MED_PRESCRIPTION(PRESCRIPTIONID, COMPANYID, FYEARID)
  ON DELETE CASCADE;

ALTER TABLE INV_SUBSTANCE MODIFY MNEMONIC(VARCHAR2(100));
ALTER TABLE INV_GROUPATC MODIFY MNEMONIC(VARCHAR2(100));

ALTER TABLE INV_ITEMSUBSTANCE ADD(
  CONCENTRATIONEXPRESSION VARCHAR2(100),
  CONCENTRATIONQUA FLOAT(126),
  CONCENTRATIONUNIT VARCHAR2(50)
);


CREATE TABLE MED_DRUGADMINISTRATION(
  COMPANYID NUMBER(38) NOT NULL,
  FYEARID NUMBER(38) NOT NULL,
  DRUGADMINISTRATIONID NUMBER(38) NOT NULL,
  ORDERHEADERID NUMBER(38) NOT NULL,
  ORDERDETAILID NUMBER(38) NOT NULL,
  ORDERRECURRENCEID NUMBER(38),
  PRESCRIPTIONID NUMBER(38) NOT NULL,
  VISITID NUMBER(38) NOT NULL,
  PRESCRIPTIONDATE DATE,
  PRESCRIPTIONTIME TIMESTAMP(6),
  ADMINISTRATIONDATE DATE NOT NULL,
  ADMINISTRATIONTIME TIMESTAMP(6) NOT NULL,
  PRESCRITEMID NUMBER(38),
  PRESCRUNITOFMEASUREID NUMBER(38),
  PRESCRQUA FLOAT(126),
  INVITEMID NUMBER(38) NOT NULL,
  UNITOFMEASUREID NUMBER(38) NOT NULL,
  QUA FLOAT(126) NOT NULL,
  SUBSTANCEID NUMBER(38),
  ISDRUGREJECTED VARCHAR2(1) DEFAULT '0' NOT NULL,
  COMMENTS VARCHAR2(50),
  REJECTIONREASONINDICATOR NUMBER(38)
);
ALTER TABLE MED_DRUGADMINISTRATION
  ADD CONSTRAINT MED_DRUGADMINISTRATION_PK
  PRIMARY KEY(DRUGADMINISTRATIONID, COMPANYID);

ALTER TABLE MED_DRUGADMINISTRATION
  ADD CONSTRAINT MED_ORDERHD_DRUGADMIN_FK
  FOREIGN KEY(ORDERHEADERID, COMPANYID, FYEARID)
  REFERENCES MED_ORDERHEADER(ORDERHEADERID, COMPANYID, FYEARID);

ALTER TABLE MED_DRUGADMINISTRATION
  ADD CONSTRAINT MED_ORDERDT_DRUGADMIN_FK
  FOREIGN KEY(ORDERDETAILID, COMPANYID, FYEARID)
  REFERENCES MED_ORDERDETAIL(ORDERDETAILID, COMPANYID, FYEARID);

ALTER TABLE MED_DRUGADMINISTRATION
  ADD CONSTRAINT MED_ORDERREC_DRUGADMIN_FK
  FOREIGN KEY(ORDERRECURRENCEID, COMPANYID, FYEARID)
  REFERENCES MED_ORDERRECURRENCE(ORDERRECURRENCEID, COMPANYID, FYEARID);

ALTER TABLE MED_DRUGADMINISTRATION
  ADD CONSTRAINT INV_ITEM_DRUGADMIN_FK
  FOREIGN KEY(INVITEMID, COMPANYID, FYEARID)
  REFERENCES INV_ITEM(INVITEMID, COMPANYID, FYEARID);

ALTER TABLE MED_DRUGADMINISTRATION
  ADD CONSTRAINT INV_ITEM_DRUGPRESCR_FK
  FOREIGN KEY(PRESCRITEMID, COMPANYID, FYEARID)
  REFERENCES INV_ITEM(INVITEMID, COMPANYID, FYEARID);

ALTER TABLE MED_DRUGADMINISTRATION
  ADD CONSTRAINT PTA_VISIT_DRUGADMIN_FK
  FOREIGN KEY(VISITID, COMPANYID, FYEARID)
  REFERENCES PTA_VISIT(VISITID, COMPANYID, FYEARID);

ALTER TABLE MED_DRUGADMINISTRATION
  ADD CONSTRAINT INV_SUBST_DRUGADMIN_FK
  FOREIGN KEY(SUBSTANCEID, COMPANYID)
  REFERENCES INV_SUBSTANCE(SUBSTANCEID, COMPANYID);

CREATE INDEX MED_DRUGADMINISTRATION_DATE ON MED_DRUGADMINISTRATION(ADMINISTRATIONDATE, COMPANYID, FYEARID);
CREATE INDEX PTA_VISIT_DRUGADMIN_FK ON MED_DRUGADMINISTRATION(VISITID, COMPANYID, FYEARID);