CREATE TABLE MED_SECURITYROLE(
  SECURITYROLEID NUMBER(38) NOT NULL,
  COMPANYID NUMBER(38) NOT NULL,
  MNEMONIC VARCHAR2(20) NOT NULL,
  DESCR VARCHAR2(100) NOT NULL,
  ISACTIVE VARCHAR2(1) NOT NULL,
  COMMENTS VARCHAR2(200)
  );
ALTER TABLE MED_SECURITYROLE ADD CONSTRAINT MED_SECURITYROLE_PK PRIMARY KEY(SECURITYROLEID, COMPANYID);

CREATE TABLE MED_SECURITYPROFILE(
  SECURITYPROFILEID NUMBER(38) NOT NULL,
  COMPANYID NUMBER(38) NOT NULL,
  MNEMONIC VARCHAR2(20) NOT NULL,
  DESCR VARCHAR2(100) NOT NULL,
  ISACTIVE VARCHAR2(1) NOT NULL,
  ISDEFAULT VARCHAR2(1) NOT NULL,
  COMMENTS VARCHAR2(200));
ALTER TABLE MED_SECURITYPROFILE ADD CONSTRAINT MED_SECURITYPROFILE_PK PRIMARY KEY(SECURITYPROFILEID, COMPANYID);

CREATE TABLE MED_OBSPARAMSECURITY(
  OBSPARAMSECURITYID NUMBER(38) NOT NULL,
  PARAMETERID NUMBER(38) NOT NULL,
  SECURITYPROFILEID NUMBER(38) NOT NULL,
  COMPANYID NUMBER(38) NOT NULL,
  VIEWSECURITYSTAMP NUMBER(38) NOT NULL,
  UPDATESECURITYSTAMP NUMBER(38) NOT NULL,
  DELETESECURITYSTAMP NUMBER(38) NOT NULL
  );
ALTER TABLE MED_OBSPARAMSECURITY ADD CONSTRAINT MED_OBSPARAMSECURITY_PK PRIMARY KEY(OBSPARAMSECURITYID, COMPANYID);
ALTER TABLE MED_OBSPARAMSECURITY ADD CONSTRAINT MED_OBSPARAM_SECURITY_FK
  FOREIGN KEY(PARAMETERID, COMPANYID)
  REFERENCES MED_OBSPARAM(PARAMETERID, COMPANYID)
  ON DELETE CASCADE;
ALTER TABLE MED_OBSPARAMSECURITY ADD CONSTRAINT MED_SECURPROF_OBSPSECURITY_FK
  FOREIGN KEY(SECURITYPROFILEID, COMPANYID)
  REFERENCES MED_SECURITYPROFILE(SECURITYPROFILEID, COMPANYID);
CREATE INDEX MED_OBSPARAM_SECURITY_FK ON MED_OBSPARAMSECURITY(PARAMETERID, COMPANYID);
CREATE INDEX MED_SECURPROF_OBSPSECURITY_FK ON MED_OBSPARAMSECURITY(SECURITYPROFILEID, COMPANYID);

ALTER TABLE PTA_VISIT ADD (
  SECURITYPROFILEID NUMBER(38),
  OWNERUSERNAME VARCHAR2(20)
  );
ALTER TABLE PTA_VISIT ADD CONSTRAINT MED_SECURITYPROFILE_VISIT_FK
  FOREIGN KEY(SECURITYPROFILEID, COMPANYID)
  REFERENCES MED_SECURITYPROFILE (SECURITYPROFILEID, COMPANYID);
ALTER TABLE PTA_VISIT ADD CONSTRAINT SYS_USER_VISIT_FK
  FOREIGN KEY(OWNERUSERNAME, COMPANYID)
  REFERENCES SYS_USER(USERNAME, COMPANYID);

CREATE TABLE MED_VISITSECURITYROLE(
  VISITSECURITYROLEID NUMBER(38) NOT NULL,
  VISITID NUMBER(38) NOT NULL,
  COMPANYID NUMBER(38) NOT NULL,
  FYEARID NUMBER(38) NOT NULL,
  SECURITYROLEID NUMBER(38) NOT NULL,
  USERNAME VARCHAR2(20),
  ROLEID NUMBER(38)
  );
ALTER TABLE MED_VISITSECURITYROLE ADD CONSTRAINT MED_VISITSECURITYROLE_PK PRIMARY KEY(VISITSECURITYROLEID, COMPANYID);
ALTER TABLE MED_VISITSECURITYROLE ADD CONSTRAINT PTA_VISIT_VISITSECURITYROLE_FK
  FOREIGN KEY(VISITID, COMPANYID, FYEARID)
  REFERENCES PTA_VISIT(VISITID, COMPANYID, FYEARID)
  ON DELETE CASCADE;
ALTER TABLE MED_VISITSECURITYROLE ADD CONSTRAINT MED_SECROLE_VISITSECROLE_FK
  FOREIGN KEY(SECURITYROLEID, COMPANYID)
  REFERENCES MED_SECURITYROLE(SECURITYROLEID, COMPANYID);
ALTER TABLE MED_VISITSECURITYROLE ADD CONSTRAINT SYS_USER_MED_VISITSECROLE_FK
  FOREIGN KEY(USERNAME, COMPANYID)
  REFERENCES SYS_USER(USERNAME, COMPANYID);
ALTER TABLE MED_VISITSECURITYROLE ADD CONSTRAINT SYS_ROLE_MED_VISITSECROLE_FK
  FOREIGN KEY(ROLEID, COMPANYID)
  REFERENCES SYS_ROLE(ROLEID, COMPANYID);
CREATE INDEX PTA_VISIT_VISITSECURITYROLE_FK ON MED_VISITSECURITYROLE(VISITID, COMPANYID, FYEARID);

ALTER TABLE MED_OBSERVATION ADD (
  OWNERUSERNAME VARCHAR2(20),
  GRANTVIEWSECURITYSTAMP NUMBER(38),
  REVOKEVIEWSECURITYSTAMP NUMBER(38),
  GRANTUPDATESECURITYSTAMP NUMBER(38),
  REVOKEUPDATESECURITYSTAMP NUMBER(38),
  GRANTDELETESECURITYSTAMP NUMBER(38),
  REVOKEDELETESECURITYSTAMP NUMBER(38)
  );
ALTER TABLE MED_OBSERVATION ADD CONSTRAINT SYS_USER_OBSERVATION_FK
  FOREIGN KEY(OWNERUSERNAME, COMPANYID)
  REFERENCES SYS_USER(USERNAME, COMPANYID);

/**
CREATE TABLE MED_OBSERVATIONSECURITYROLE(
  OBSERVATIONSECURITYROLEID NUMBER(38) NOT NULL,
  OBSERVATIONID NUMBER(38) NOT NULL,
  COMPANYID NUMBER(38) NOT NULL,
  SINCEDATE DATE NOT NULL,
  TILLDATE DATE,
  SECURITYROLEID NUMBER(38) NOT NULL,
  USERNAME VARCHAR2(20),
  ROLEID NUMBER(38)
  );
ALTER TABLE MED_OBSERVATIONSECURITYROLE ADD CONSTRAINT MED_OBSERVATIONSECURITYROLE_PK PRIMARY KEY(OBSERVATIONSECURITYROLEID, COMPANYID);
  */

ALTER TABLE MED_SERVICE ADD (
  OWNERUSERNAME VARCHAR2(20),
  GRANTVIEWSECURITYSTAMP NUMBER(38),
  REVOKEVIEWSECURITYSTAMP NUMBER(38),
  GRANTUPDATESECURITYSTAMP NUMBER(38),
  REVOKEUPDATESECURITYSTAMP NUMBER(38),
  GRANTDELETESECURITYSTAMP NUMBER(38),
  REVOKEDELETESECURITYSTAMP NUMBER(38)
);
ALTER TABLE MED_SERVICE ADD CONSTRAINT MED_SERVICE_OBSERVATION_FK
  FOREIGN KEY(OWNERUSERNAME, COMPANYID)
  REFERENCES SYS_USER(USERNAME, COMPANYID);

ALTER TABLE MED_MEDICALPROC ADD (
  OWNERUSERNAME VARCHAR2(20),
  GRANTVIEWSECURITYSTAMP NUMBER(38),
  REVOKEVIEWSECURITYSTAMP NUMBER(38),
  GRANTUPDATESECURITYSTAMP NUMBER(38),
  REVOKEUPDATESECURITYSTAMP NUMBER(38),
  GRANTDELETESECURITYSTAMP NUMBER(38),
  REVOKEDELETESECURITYSTAMP NUMBER(38)
);
ALTER TABLE MED_MEDICALPROC ADD CONSTRAINT MED_MEDICALPROC_OBSERVATION_FK
  FOREIGN KEY(OWNERUSERNAME, COMPANYID)
  REFERENCES SYS_USER(USERNAME, COMPANYID);

ALTER TABLE PBL_DOCTORROLE ADD (
  ISVISITOWNER VARCHAR2(1),
  SECURITYROLEID NUMBER(38)
  );
UPDATE PBL_DOCTORROLE SET ISVISITOWNER = '0';
COMMIT;
ALTER TABLE PBL_DOCTORROLE MODIFY ISVISITOWNER NOT NULL;

ALTER TABLE PTA_DOCTOR ADD USERNAME VARCHAR2(20);
ALTER TABLE PTA_DOCTOR ADD CONSTRAINT SYS_USER_PTA_DOCTOR_FK
  FOREIGN KEY (USERNAME, COMPANYID)
  REFERENCES  SYS_USER(USERNAME, COMPANYID);
CREATE INDEX SYS_USER_PTA_DOCTOR_FK ON PTA_DOCTOR(USERNAME, COMPANYID);

CREATE TABLE MED_FACILITYSECURITYROLE(
  FACILITYSECURITYROLEID NUMBER(38) NOT NULL,
  FACILITYID VARCHAR2(40) NOT NULL,
  COMPANYID NUMBER(38) NOT NULL,
  FYEARID NUMBER(38) NOT NULL,
  SECURITYROLEID NUMBER(38) NOT NULL,
  VALIDSINCEDATE DATE NOT NULL,
  VALIDTILLDATE DATE,
  USERNAME VARCHAR2(20),
  ROLEID NUMBER(38)
  );
ALTER TABLE MED_FACILITYSECURITYROLE ADD CONSTRAINT MED_FACILITYSECURITYROLE_PK PRIMARY KEY(FACILITYSECURITYROLEID, COMPANYID);
ALTER TABLE MED_FACILITYSECURITYROLE ADD CONSTRAINT PTA_FACILITY_SECURITYROLE_FK
  FOREIGN KEY(FACILITYID, COMPANYID, FYEARID)
  REFERENCES PTA_FACILITY(FACILITYID, COMPANYID, FYEARID)
  ON DELETE CASCADE;
ALTER TABLE MED_FACILITYSECURITYROLE ADD CONSTRAINT MED_SECROLE_FACILITYSECROLE_FK
  FOREIGN KEY(SECURITYROLEID, COMPANYID)
  REFERENCES MED_SECURITYROLE(SECURITYROLEID, COMPANYID);
ALTER TABLE MED_FACILITYSECURITYROLE ADD CONSTRAINT SYS_USER_MED_FACILSECROLE_FK
  FOREIGN KEY(USERNAME, COMPANYID)
  REFERENCES SYS_USER(USERNAME, COMPANYID);
ALTER TABLE MED_FACILITYSECURITYROLE ADD CONSTRAINT SYS_ROLE_MED_FACILSECROLE_FK
  FOREIGN KEY(ROLEID, COMPANYID)
  REFERENCES SYS_ROLE(ROLEID, COMPANYID);
CREATE INDEX MED_FACILITY_SECURITYROLE_FK ON MED_FACILITYSECURITYROLE(FACILITYID, COMPANYID, FYEARID);
