create table AST_DIAVGIAPARAMS
(
  COMPANYID NUMBER(38),
  ORGANIZATIONID VARCHAR2(20),
  FINANCEDEPTID VARCHAR2(20),
  BUDGETRESUSERNAME VARCHAR2(20),
  BUDGETRESPASSWORD VARCHAR2(20)
);
alter table AST_DIAVGIAPARAMS
  add constraint AST_DIAVGIAPARAMS_PK
   primary key(companyid);