insert into sys_object (objectid,descr,Objecttype,yearmigrationorder,yearmigrationaction,ismigrated)
values ('PBL_DOCTORRULEDOCTORLNK','PBL_DOCTORRULEDOCTORLNK',1,232,1,1);
insert into sys_object (objectid,descr,Objecttype,yearmigrationorder,yearmigrationaction,ismigrated)
values ('INV_ITEMSTOREACCESS','INV_ITEMSTOREACCESS',1,233,1,1);
insert into sys_object (objectid,descr,Objecttype,yearmigrationorder,yearmigrationaction,ismigrated)
values ('PBL_CARDPARAMETERS','PBL_CARDPARAMETERS',1,234,1,1);
insert into sys_object (objectid,descr,Objecttype,yearmigrationorder,yearmigrationaction,ismigrated)
values ('GLG_JOURNALPROTOTYPE','GLG_JOURNALPROTOTYPE',1,235,1,1);
insert into sys_object (objectid,descr,Objecttype,yearmigrationorder,yearmigrationaction,ismigrated)
values ('GLG_JOURNALACCOUNTPROTOTYPE','GLG_JOURNALACCOUNTPROTOTYPE',1,236,1,1);
COMMIT;
