alter table PBL_CHARGEHEADER add EOPYYPARAMETERSID number(38);
alter table PBL_CHARGEHEADER
  add constraint
  PTA_EOPYYPARAMS_CHARGEHD_FK
  foreign key(EOPYYPARAMETERSID, COMPANYID, FYEARID)
  references PTA_EOPYYPARAMETERS(EOPYYPARAMETERSID, COMPANYID, FYEARID);

