alter table MED_SERVICE add (
  ISREORDERINGSERVICE VARCHAR2(1) DEFAULT '0' NOT NULL,
  REORDERSCHEDULEDATE DATE
);

alter table MED_ORDERHEADER
  add SERVICEID NUMBER(38);
alter table MED_ORDERHEADER
  add constraint MED_SERVICE_ORDERHD_FK
  foreign key (SERVICEID, COMPANYID)
  references MED_SERVICE(SERVICEID, COMPANYID);
create index MED_SERVICE_ORDERHD_FK
  on MED_ORDERHEADER
  (SERVICEID, COMPANYID);