alter table PTA_PARAMETERS add ORDERMATRIXID number(38);
alter table PTA_PARAMETERS add ORDERPERSONID number(38);
alter table PTA_PARAMETERS add ORDERFACILITYID VARCHAR2(40);

alter table PTA_PARAMETERS
  add constraint FK_PTA_PARAMS_ORDERPERSON foreign key (ORDERPERSONID, COMPANYID, FYEARID)
  references med_orderperson (ORDERPERSONID, COMPANYID, FYEARID);
alter table PTA_PARAMETERS
  add constraint FK_PTA_PARAMS_ORDERFACIL foreign key (ORDERFACILITYID, COMPANYID, FYEARID)
  references pta_facility (FACILITYID, COMPANYID, FYEARID);

alter table PTA_VISITADMISSION add SERVICEMASTERGROUPINGID number(38);
alter table PTA_VISITADMISSION add SERVICEMASTERGROUPINGCODE VARCHAR2(40);

alter table PTA_VISITADMISSION
  add constraint FK_SRVMASTERGRPING_VISITADM foreign key (SERVICEMASTERGROUPINGID, SERVICEMASTERGROUPINGCODE, COMPANYID)
  references med_servicemastergroupingcode (SERVICEMASTERGROUPINGID, SERVICEMASTERGROUPINGCODE, COMPANYID);

create index FK_SRVMASTERGRPING_VISITADM on PTA_VISITADMISSION (SERVICEMASTERGROUPINGID, SERVICEMASTERGROUPINGCODE, COMPANYID);

alter table MED_ORDERHEADER add VISITADMISSIONID number(38);

alter table MED_ORDERHEADER
  add constraint FK_VISITADM_MEDORDERHD foreign key (VISITADMISSIONID, COMPANYID, FYEARID)
  references PTA_VISITADMISSION (VISITADMISSIONID, COMPANYID, FYEARID);

create index FK_VISITADM_MEDORDERHD on MED_ORDERHEADER (visitadmissionid, companyid, fyearid);
