create table INV_SELLPERCHEADER (
  SELLPERCHEADERID NUMBER(38) not null,
  COMPANYID        NUMBER(38) not null,
  FYEARID          NUMBER(38) not null,
  MNEMONIC         VARCHAR2(20) not null,
  DESCR            VARCHAR2(50) not null,
  ISACTIVE         VARCHAR2(1) not null
);

alter table INV_SELLPERCHEADER
  add constraint PK_INV_SELLPERCHEADER
  primary key (SELLPERCHEADERID, COMPANYID, FYEARID);

create table INV_SELLPERCDETAIL (
  SELLPERCDETAILID NUMBER(38) not null,
  COMPANYID        NUMBER(38) not null,
  FYEARID          NUMBER(38) not null,
  SELLPERCHEADERID NUMBER(38) not null,
  VALIDSINCEDATE   DATE not null,
  VALIDTILLDATE    DATE,
  PERC             FLOAT not null
);

alter table INV_SELLPERCDETAIL
  add constraint PK_INV_SELLPERCDETAIL
  primary key (SELLPERCDETAILID, COMPANYID, FYEARID);

alter table INV_SELLPERCDETAIL
  add constraint INV_SELLPERCHD_DT_FK
  foreign key (SELLPERCHEADERID, COMPANYID, FYEARID)
  references INV_SELLPERCHEADER(SELLPERCHEADERID, COMPANYID, FYEARID)
  on delete cascade;
create index INV_SELLPERCHD_DT_FK on INV_SELLPERCDETAIL (SELLPERCHEADERID, COMPANYID, FYEARID);


create table INV_PRICELISTHEADER (
  PRICELISTHEADERID      NUMBER(38) not null,
  COMPANYID              NUMBER(38) not null,
  FYEARID                NUMBER(38) not null,
  MNEMONIC               VARCHAR2(20) not null,
  DESCR                  VARCHAR2(50) not null,
  COMMENTS               VARCHAR2(200),
  VALIDSINCEDATE         DATE not null,
  ISACTIVE               VARCHAR2(1) not null,
  PRICELISTTYPEINDICATOR NUMBER(38) not null
);

alter table INV_PRICELISTHEADER
  add constraint PK_INV_PRICELISTHEADER
  primary key (PRICELISTHEADERID, COMPANYID, FYEARID);

create table INV_PRICELISTDETAIL (
  PRICELISTDETAILID      NUMBER(38) not null,
  COMPANYID              NUMBER(38) not null,
  FYEARID                NUMBER(38) not null,
  PRICELISTHEADERID      NUMBER(38) not null,
  VALIDSINCEDATE         DATE not null,
  VALIDTILLDATE          DATE,
  INVITEMGROUPINGID      NUMBER(38),
  INVITEMGROUPINGCODE    VARCHAR2(40),
  RELPRICELISTHEADERID   NUMBER(38),
  INVITEMID              NUMBER(38),
  PRICINGPOLICYINDICATOR NUMBER(38) not null,
  SELLPERCHEADERID       NUMBER(38),
  PRICE                  FLOAT
);

alter table INV_PRICELISTDETAIL
  add constraint PK_INV_PRICELISTDETAIL
  primary key (PRICELISTDETAILID, COMPANYID, FYEARID);
alter table INV_PRICELISTDETAIL
  add constraint INV_ITEM_PRICELISTDETAIL_FK
  foreign key (INVITEMID, FYEARID, COMPANYID)
  references INV_ITEM (INVITEMID, FYEARID, COMPANYID);
alter table INV_PRICELISTDETAIL
  add constraint INV_ITEMGRPCODE_PRICELISTDT_FK
  foreign key (INVITEMGROUPINGID, INVITEMGROUPINGCODE, COMPANYID, FYEARID)
  references INV_ITEMGROUPINGCODE (INVITEMGROUPINGID, INVITEMGROUPINGCODE, COMPANYID, FYEARID);
alter table INV_PRICELISTDETAIL
  add constraint INV_ITEMGRP_PRICELISTDETAIL_FK
  foreign key (INVITEMGROUPINGID, COMPANYID, FYEARID)
  references INV_ITEMGROUPING (INVITEMGROUPINGID, COMPANYID, FYEARID);
alter table INV_PRICELISTDETAIL
  add constraint INV_PRICELISRHEADER_DT_FK
  foreign key (PRICELISTHEADERID, COMPANYID, FYEARID)
  references INV_PRICELISTHEADER (PRICELISTHEADERID, COMPANYID, FYEARID)
  on delete cascade;
alter table INV_PRICELISTDETAIL
  add constraint INV_PRICELISTDT_RELPRICE_FK
  foreign key (RELPRICELISTHEADERID, COMPANYID, FYEARID)
  references INV_PRICELISTHEADER (PRICELISTHEADERID, COMPANYID, FYEARID);
alter table INV_PRICELISTDETAIL
  add constraint INV_SELLPERCHD_PRICELISTDT_FK
  foreign key (SELLPERCHEADERID, COMPANYID, FYEARID)
  references INV_SELLPERCHEADER (SELLPERCHEADERID, COMPANYID, FYEARID);

create index INV_ITEM_PRICELISTDETAIL_FK
  on INV_PRICELISTDETAIL (INVITEMID, COMPANYID, FYEARID);
create index INV_PRICELISRHEADER_DT_FK
  on INV_PRICELISTDETAIL (PRICELISTHEADERID, COMPANYID, FYEARID);

alter table FIN_TRANSPARTY add PRICELISTHEADERID NUMBER(38);
alter table FIN_TRANSPARTY
  add constraint INV_PRICELIST_TRANSPARTY_FK
   foreign key (PRICELISTHEADERID, COMPANYID, FYEARID)
   references INV_PRICELISTHEADER (PRICELISTHEADERID, COMPANYID, FYEARID);
