alter table INV_STORE add CONTRACTQUAALERTINDICATOR NUMBER(38);
alter table INV_STORE add CONTRACTPRICEALERTINDICATOR NUMBER(38);
UPDATE INV_STORE SET CONTRACTQUAALERTINDICATOR = 1;
UPDATE INV_STORE SET CONTRACTPRICEALERTINDICATOR = 1;
COMMIT;
