ALTER TABLE PTA_EOPYYPARAMETERS ADD(
  ISDEFAULT VARCHAR2(1) DEFAULT '1' NOT NULL,
  ISACTIVE VARCHAR2(1) DEFAULT '1' NOT NULL,
  EPRESCR_USERID VARCHAR2(15),
  EOPYYPARAMETERSID NUMBER(38) DEFAULT 1 NOT NULL,
  DESCR VARCHAR2(50) DEFAULT 'ΒΑΣΙΚΗ ΣΥΜΒΑΣΗ' NOT NULL,
  EPRESCR_DEFAULTMAINPHONE VARCHAR2(15),
  EPRESCR_DEFAULTMOBILEPHONE VARCHAR2(15)
);
ALTER TABLE PTA_EOPYYPARAMETERS DROP PRIMARY KEY;
ALTER TABLE PTA_EOPYYPARAMETERS
  ADD CONSTRAINT PTA_EOPYYPARAMETERS_PK
  PRIMARY KEY(EOPYYPARAMETERSID, COMPANYID, FYEARID);

CREATE SEQUENCE PTA_EOPYYPARAMETERS_SEQ START WITH 2 INCREMENT BY 1 NOCACHE;