CREATE TABLE MED_MSGEVENT (
  COMPANYID NUMBER(38) NOT NULL,
  MSGEVENTID NUMBER(38) NOT NULL,
  ISACTIVE VARCHAR2(1) NOT NULL,
  PAGEFORM VARCHAR2(100) NOT NULL,
  CLASSNAME VARCHAR2(200) NOT NULL,
  ACTION NUMBER(38) NOT NULL,
  MESSAGE VARCHAR2(100) NOT NULL,
  REDIRECTURL VARCHAR2(100),
  APPLYCONDITION VARCHAR2(200)
);
ALTER TABLE MED_MSGEVENT
  ADD CONSTRAINT MED_MSGEVENT_PK
  PRIMARY KEY (MSGEVENTID, COMPANYID);

CREATE TABLE MED_MSGEVENTUSERS (
  MSGEVENTUSERSID NUMBER(38) NOT NULL,
  COMPANYID NUMBER(38) NOT NULL,
  MSGEVENTID NUMBER(38) NOT NULL,
  USERNAME VARCHAR2(20),
  ROLEID NUMBER(38),
  SECURITYROLEID NUMBER(38)
);
ALTER TABLE MED_MSGEVENTUSERS
  ADD CONSTRAINT MED_MSGEVENTUSERS_PK
  PRIMARY KEY (MSGEVENTUSERSID, COMPANYID);
ALTER TABLE MED_MSGEVENTUSERS
  ADD CONSTRAINT MED_MSGEVENT_USERS_FK
  FOREIGN KEY (MSGEVENTID, COMPANYID)
  REFERENCES MED_MSGEVENT(MSGEVENTID, COMPANYID)
  ON DELETE CASCADE;
ALTER TABLE MED_MSGEVENTUSERS
  ADD CONSTRAINT SYS_USER_MSGEVENTUSERS_FK
  FOREIGN KEY (USERNAME, COMPANYID)
  REFERENCES SYS_USER(USERNAME, COMPANYID);
ALTER TABLE MED_MSGEVENTUSERS
  ADD CONSTRAINT SYS_ROLE_MSGEVENTUSERS_FK
  FOREIGN KEY (ROLEID, COMPANYID)
  REFERENCES SYS_ROLE(ROLEID, COMPANYID);
ALTER TABLE MED_MSGEVENTUSERS
  ADD CONSTRAINT MED_SECURITYROLE_MSGEVENT_FK
  FOREIGN KEY (SECURITYROLEID, COMPANYID)
  REFERENCES MED_SECURITYROLE(SECURITYROLEID, COMPANYID);

ALTER TABLE MED_MESSAGE ADD (
  MSGEVENTID NUMBER(38),
  REDIRECTURL VARCHAR2(200)
);
ALTER TABLE MED_MESSAGE
  ADD CONSTRAINT MED_MSGEVENT_MSG_FK
  FOREIGN KEY (MSGEVENTID, COMPANYID)
  REFERENCES MED_MSGEVENT (MSGEVENTID, COMPANYID);
ALTER TABLE MED_MESSAGE MODIFY VISITID NULL;